## Importing functions

In [73]:
from functions.gpkg_funcs import (
    import_gpkg_func,
    reproject_gpkg_func,
)

from functions.idx_pixel_count_funcs import (
    idx_per_row_area_func,
)

from functions.idx_to_gdf_or_plot_funcs import (
    idx_df_to_gdf_func,
)

from functions.training_validation_split_funcs import (
    training_validation_split_func,
)

## Setting Directory

In [74]:
from paths.OG_paths import(
    #######################################
    #  03_training_validation_data_split  #
    #######################################
    # | n01_build_selected_pixels_idx_dfs |
    # +===================================+
    # --- manual inspected pixeled gpkg --- #    
    habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gpkg_path,
    
    # --- selected pixels IDX dfs --- #
    idx__FC_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD1_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD2_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD3_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD4_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD5_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__s1_plusOW_p80_selected_gelderland_tmp2_df_path,


    # +===================================+
    # |   n03_training_validation_split   |
    # +===================================+
    # --- idx training validation dfs --- #
    #WD1
    idx__WD1_plusOW_p80_tmp2_training_ML_at1__gelderland__df_path,
    idx__WD1_plusOW_p80_tmp2_validation_ML_at1__gelderland__df_path,
    #WD2
    idx__WD2_plusOW_p80_tmp2_training_ML_at1__gelderland__df_path,
    idx__WD2_plusOW_p80_tmp2_validation_ML_at1__gelderland__df_path,
    #WD3
    idx__WD3_plusOW_p80_tmp2_training_ML_at1__gelderland__df_path,
    idx__WD3_plusOW_p80_tmp2_validation_ML_at1__gelderland__df_path,
    #WD4
    idx__WD4_plusOW_p80_tmp2_training_ML_at1__gelderland__df_path,
    idx__WD4_plusOW_p80_tmp2_validation_ML_at1__gelderland__df_path,
    #WD5
    idx__WD5_plusOW_p80_tmp2_training_ML_at1__gelderland__df_path,
    idx__WD5_plusOW_p80_tmp2_validation_ML_at1__gelderland__df_path,

    # --- training validation GPKGs UTM32631 --- #
    # WD1
    training_pixels__WD1_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg_path,
    validation_pixels__WD1_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg_path,
    # WD2
    training_pixels__WD2_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg_path,
    validation_pixels__WD2_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg_path,
    # WD3
    training_pixels__WD3_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg_path,
    validation_pixels__WD3_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg_path,
    # WD4
    training_pixels__WD4_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg_path,
    validation_pixels__WD4_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg_path,
    # WD5
    training_pixels__WD5_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg_path,
    validation_pixels__WD5_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg_path,
)

## Importing packages

In [75]:
import pandas as pd

## Importing files

In [76]:
habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf = import_gpkg_func(
    gdf_path=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gpkg_path, 
    layer='habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__layer', 
    index_col='index',
)

In [77]:
idx__FC_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__FC_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WD1_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD1_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WD2_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD2_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WD3_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD3_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WD4_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD4_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WD5_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD5_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__s1_plusOW_p80_selected_gelderland_tmp2_df = pd.read_pickle(idx__s1_plusOW_p80_selected_gelderland_tmp2_df_path)

## Calculating the unique area of each pixel

_This step calculates the total area of the unique ID's. If a ID is present in multiple columns, then it is only taken into account once. Based on this a list is build that determines the amount of area that should be included in the training/validation set_

### WD1

In [78]:
WD1_area_text = idx_per_row_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD1_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
    as_text=True,
)

print("WD1 areas per row:\n" + WD1_area_text)

WD1 areas per row:
Remaining: 304500.61 pixels
Wet Nature: 1537.11 pixels
Open water: 1330.00 pixels

In [79]:
WD1_at1_dict = {
    "Remaining": 3000,
    "Wet Nature": 1400,
    "Open water": 300,
}

### WD2

In [80]:
WD2_area_text = idx_per_row_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD2_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
    as_text=True,
)

print("WD2 areas per row:\n" + WD2_area_text)

WD2 areas per row:
Remaining: 304500.61 pixels
Semi-Wet Nature: 1289.76 pixels
Wet Nature: 247.35 pixels
Open water: 1330.00 pixels

In [81]:
WD2_at1_dict = {
    "Remaining": 1250,
    "Wet Nature": 250,
    "Semi-Wet Nature": 500,
    "Open water": 250,
}

### WD3

In [82]:
WD3_area_text = idx_per_row_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD3_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
    as_text=True,
)

print("WD3 areas per row:\n" + WD3_area_text)

WD3 areas per row:
Remaining: 122089.61 pixels
Wet Nature: 1537.11 pixels
Open water: 1330.00 pixels

In [83]:
WD3_at1_dict = {
    "Remaining": 2500,
    "Wet Nature": 1300,
    "Open water": 300,
}

### WD4

In [84]:
WD4_area_text = idx_per_row_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD4_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
    as_text=True,
)

print("WD4 areas per row:\n" + WD4_area_text)

WD4 areas per row:
Remaining: 122089.61 pixels
Semi-Wet Nature: 1289.76 pixels
Wet Nature: 247.35 pixels
Open water: 1330.00 pixels

In [85]:
WD4_at1_dict = {
    "Remaining": 1250,
    "Semi-Wet Nature": 500,
    "Wet Nature": 250,
    "Open water": 300,
}

### WD5

In [86]:
WD5_area_text = idx_per_row_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD5_plusOW_p80__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
    as_text=True,
)

print("WD5 areas per row:\n" + WD5_area_text)

WD5 areas per row:
Remaining: 122089.61 pixels
Semi-Wet Nature: 1289.76 pixels
Open water: 1577.35 pixels

In [87]:
WD5_at1_dict = {
    "Remaining": 1250,
    "Semi-Wet Nature": 500,
    "Open water": 300,
}

## Splitting the data and saving as gpkgs

### WD1 - ML split

_attempt 1_

In [88]:
train_val__WD1_plusOW_p80_tmp2_ML_at1__gelderland__list = training_validation_split_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD1_plusOW_p80__selected__gelderland__tmp2__df,
    year_cols=idx__WD1_plusOW_p80__selected__gelderland__tmp2__df.columns,
    train_years=["2017"],
    val_years=["2018", "2019", "2020", "2021", "2022", "2023", "2024"],
    cap_pixels_by_class=WD1_at1_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    seed=42,
    area_col="bedekkingsOppervlakte1",
    pixel_area_m2=100.0,
)

idx__WD1_plusOW_p80_tmp2_training_ML_at1__gelderland__df = train_val__WD1_plusOW_p80_tmp2_ML_at1__gelderland__list[0]
idx__WD1_plusOW_p80_tmp2_validation_ML_at1__gelderland__df = train_val__WD1_plusOW_p80_tmp2_ML_at1__gelderland__list[1]
idx__WD1_plusOW_p80_tmp2_test_ML_at1__gelderland__df = train_val__WD1_plusOW_p80_tmp2_ML_at1__gelderland__list[2]
idx__WD1_plusOW_p80_tmp2_leftover_ML_at1__gelderland__df = train_val__WD1_plusOW_p80_tmp2_ML_at1__gelderland__list[3]
idx__WD1_plusOW_p80_tmp2_summary_ML_at1__gelderland__df = train_val__WD1_plusOW_p80_tmp2_ML_at1__gelderland__list[4]

In [89]:
idx__WD1_plusOW_p80_tmp2_summary_ML_at1__gelderland__df

,target_train_m2,got_train_m2,target_val_m2,got_val_m2,target_test_m2,got_test_m2,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,210000.0,212480.0,90000.0,91640.0,0.0,0.0,2128,920,0,292526,0,0,140,57,0
Wet Nature,98000.0,26500.0,42000.0,42031.0,0.0,0.0,265,423,0,244,0,0,56,7,0
Open water,21000.0,21600.0,9000.0,11800.0,0.0,0.0,216,118,0,3024,0,0,12,5,0

In [90]:
idx__WD1_plusOW_p80_tmp2_validation_ML_at1__gelderland__df

,2017,2018,2019,2020,2021,2022,2023,2024
Remaining,[],"[GI_19657_1, GI_19657_2, GI_19657_3, GI_19697_...","[GI_11438_1, GI_11438_2, GI_11438_3, GI_11438_...","[GI_10423_2, GI_10423_3, GI_10423_4, GI_10423_...","[GI_16864_1, GI_16864_10, GI_16864_11, GI_1686...","[GI_44881_1, GI_44881_10, GI_44881_11, GI_4488...","[GI_182_10, GI_182_11, GI_182_13, GI_182_14, G...",[]
Wet Nature,[],"[GI_18984_2, GI_18984_3, GI_18984_31, GI_18984...",[],"[GI_12951_1, GI_12951_2, GI_12951_3, GI_12951_...",[],"[GI_44936_1, GI_44936_10, GI_44936_11, GI_4493...",[],[]
Open water,[],[],"[lgn_plusOW_110_11, lgn_plusOW_110_12, lgn_plu...","[lgn_plusOW_533_10, lgn_plusOW_533_11, lgn_plu...",[],[],"[lgn_plusOW_77_100, lgn_plusOW_77_101, lgn_plu...","[lgn_plusOW_534_1, lgn_plusOW_534_10, lgn_plus..."

In [91]:
# Saving the training and validation idx dfs
idx__WD1_plusOW_p80_tmp2_training_ML_at1__gelderland__df.to_pickle(idx__WD1_plusOW_p80_tmp2_training_ML_at1__gelderland__df_path)
idx__WD1_plusOW_p80_tmp2_validation_ML_at1__gelderland__df.to_pickle(idx__WD1_plusOW_p80_tmp2_validation_ML_at1__gelderland__df_path)

In [ ]:
# --- WD1 ML at1 Training gpkgs --- #
training_pixels__WD1_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf = idx_df_to_gdf_func(
    idx_df=idx__WD1_plusOW_p80_tmp2_training_ML_at1__gelderland__df,
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

[path, training_pixels__WD1_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gdf] = reproject_gpkg_func(
    input_data=training_pixels__WD1_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf,
    output_epsg="EPSG:32631",
    output_gpkg=training_pixels__WD1_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg_path,
    return_gdf=False,
)

# --- WD1 ML at1 Validation gpkgs --- #
validation_pixels__WD1_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf = idx_df_to_gdf_func(
    idx_df=idx__WD1_plusOW_p80_tmp2_validation_ML_at1__gelderland__df,
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

[path, validation_pixels__WD1_plusOW_p80_tmp2_at1__gelderland__UTM32631__gdf] = reproject_gpkg_func(
    input_data=validation_pixels__WD1_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf,
    output_epsg="EPSG:32631",
    output_gpkg=validation_pixels__WD1_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg_path,
    return_gdf=False,
)

In [109]:
training_pixels__WD1_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf

,type,years,geometry
index,,,
GI_14449_1,Remaining,2017,"POLYGON ((181584.813 467442.778, 181585.143 46..."
GI_14449_10,Remaining,2017,"POLYGON ((181564.827 467443.437, 181565.156 46..."
GI_14449_11,Remaining,2017,"POLYGON ((181565.156 467453.43, 181565.485 467..."
GI_14449_12,Remaining,2017,"POLYGON ((181566.144 467483.41, 181566.473 467..."
GI_14449_13,Remaining,2017,"POLYGON ((181605.129 467452.113, 181605.458 46..."
...,...,...,...
lgn_plusOW_69_6,Open water,2017,"POLYGON ((177730.663 451252.728, 177730.992 45..."
lgn_plusOW_69_61,Open water,2017,"POLYGON ((177692.989 451323.996, 177693.317 45..."
lgn_plusOW_69_7,Open water,2017,"POLYGON ((177720.67 451253.056, 177720.998 451..."
lgn_plusOW_69_8,Open water,2017,"POLYGON ((177710.676 451253.385, 177711.005 45..."
lgn_plusOW_69_9,Open water,2017,"POLYGON ((177730.992 451262.721, 177731.32 451..."

In [110]:
validation_pixels__WD1_plusOW_p80_tmp2_at1__gelderland__UTM32631__gdf

,type,years,geometry
index,,,
GI_19657_1,Remaining,2018,"POLYGON ((688620 5787350, 688610 5787350, 6886..."
GI_19657_2,Remaining,2018,"POLYGON ((688620 5787360, 688610 5787360, 6886..."
GI_19657_3,Remaining,2018,"POLYGON ((688630 5787360, 688620 5787360, 6886..."
GI_19697_1,Remaining,2018,"POLYGON ((688940 5787630, 688930 5787630, 6889..."
GI_19697_2,Remaining,2018,"POLYGON ((688940 5787640, 688930 5787640, 6889..."
...,...,...,...
lgn_plusOW_534_50,Open water,2024,"POLYGON ((704940 5766320, 704930 5766320, 7049..."
lgn_plusOW_534_6,Open water,2024,"POLYGON ((704990 5766190, 704980 5766190, 7049..."
lgn_plusOW_534_7,Open water,2024,"POLYGON ((705000 5766200, 704990 5766200, 7049..."
lgn_plusOW_534_8,Open water,2024,"POLYGON ((704990 5766200, 704980 5766200, 7049..."
lgn_plusOW_534_9,Open water,2024,"POLYGON ((705000 5766210, 704990 5766210, 7049..."

### WD2 - ML split

_attempt 1_

In [93]:
train_val__WD2_plusOW_p80_tmp2_ML_at1__gelderland__list = training_validation_split_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD2_plusOW_p80__selected__gelderland__tmp2__df,
    year_cols=idx__WD2_plusOW_p80__selected__gelderland__tmp2__df.columns,
    train_years=["2017"],
    val_years=["2018", "2019", "2020", "2021", "2022", "2023", "2024"],
    cap_pixels_by_class=WD2_at1_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    seed=42,
    area_col="bedekkingsOppervlakte1",
    pixel_area_m2=100.0,
)

idx__WD2_plusOW_p80_tmp2_training_ML_at1__gelderland__df = train_val__WD2_plusOW_p80_tmp2_ML_at1__gelderland__list[0]
idx__WD2_plusOW_p80_tmp2_validation_ML_at1__gelderland__df = train_val__WD2_plusOW_p80_tmp2_ML_at1__gelderland__list[1]
idx__WD2_plusOW_p80_tmp2_test_ML_at1__gelderland__df = train_val__WD2_plusOW_p80_tmp2_ML_at1__gelderland__list[2]
idx__WD2_plusOW_p80_tmp2_leftover_ML_at1__gelderland__df = train_val__WD2_plusOW_p80_tmp2_ML_at1__gelderland__list[3]
idx__WD2_plusOW_p80_tmp2_summary_ML_at1__gelderland__df = train_val__WD2_plusOW_p80_tmp2_ML_at1__gelderland__list[4]

In [94]:
idx__WD2_plusOW_p80_tmp2_summary_ML_at1__gelderland__df

,target_train_m2,got_train_m2,target_val_m2,got_val_m2,target_test_m2,got_test_m2,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,87500.0,87720.0,37500.0,38800.0,0.0,0.0,878,388,0,299063,0,0,55,25,0
Semi-Wet Nature,35000.0,21500.0,15000.0,17080.0,0.0,0.0,215,173,0,357,0,0,23,5,0
Wet Nature,17500.0,5000.0,7500.0,8880.0,0.0,0.0,50,91,0,49,0,0,9,2,0
Open water,17500.0,17800.0,7500.0,8400.0,0.0,0.0,178,84,0,6952,0,0,11,3,0

In [95]:
# Saving the training and validation idx dfs
idx__WD2_plusOW_p80_tmp2_training_ML_at1__gelderland__df.to_pickle(
    idx__WD2_plusOW_p80_tmp2_training_ML_at1__gelderland__df_path
)
idx__WD2_plusOW_p80_tmp2_validation_ML_at1__gelderland__df.to_pickle(
    idx__WD2_plusOW_p80_tmp2_validation_ML_at1__gelderland__df_path
)

In [96]:
# --- WD2 ML at1 Training gpkgs --- #
training_pixels__WD2_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf = idx_df_to_gdf_func(
    idx_df=idx__WD2_plusOW_p80_tmp2_training_ML_at1__gelderland__df,
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

[path, training_pixels__WD2_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gdf] = reproject_gpkg_func(
    input_data=training_pixels__WD2_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf,
    output_epsg="EPSG:32631",
    output_gpkg=training_pixels__WD2_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg_path,
    return_gdf=True,
)

# --- WD2 ML at1 Validation gpkgs --- #
validation_pixels__WD2_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf = idx_df_to_gdf_func(
    idx_df=idx__WD2_plusOW_p80_tmp2_validation_ML_at1__gelderland__df,
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

[path, validation_pixels__WD2_plusOW_p80_tmp2_at1__gelderland__UTM32631__gdf] = reproject_gpkg_func(
    input_data=validation_pixels__WD2_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf,
    output_epsg="EPSG:32631",
    output_gpkg=validation_pixels__WD2_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg_path,
    return_gdf=True,
)

### WD3 - ML split

In [97]:
train_val__WD3_plusOW_p80_tmp2_ML_at1__gelderland__list = training_validation_split_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD3_plusOW_p80__selected__gelderland__tmp2__df,
    year_cols=idx__WD3_plusOW_p80__selected__gelderland__tmp2__df.columns,
    train_years=["2017"],
    val_years=["2018", "2019", "2020", "2021", "2022", "2023", "2024"],
    cap_pixels_by_class=WD3_at1_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    seed=42,
    area_col="bedekkingsOppervlakte1",
    pixel_area_m2=100.0,
)

idx__WD3_plusOW_p80_tmp2_training_ML_at1__gelderland__df = train_val__WD3_plusOW_p80_tmp2_ML_at1__gelderland__list[0]
idx__WD3_plusOW_p80_tmp2_validation_ML_at1__gelderland__df = train_val__WD3_plusOW_p80_tmp2_ML_at1__gelderland__list[1]
idx__WD3_plusOW_p80_tmp2_test_ML_at1__gelderland__df = train_val__WD3_plusOW_p80_tmp2_ML_at1__gelderland__list[2]
idx__WD3_plusOW_p80_tmp2_leftover_ML_at1__gelderland__df = train_val__WD3_plusOW_p80_tmp2_ML_at1__gelderland__list[3]
idx__WD3_plusOW_p80_tmp2_summary_ML_at1__gelderland__df = train_val__WD3_plusOW_p80_tmp2_ML_at1__gelderland__list[4]

In [98]:
idx__WD3_plusOW_p80_tmp2_summary_ML_at1__gelderland__df

,target_train_m2,got_train_m2,target_val_m2,got_val_m2,target_test_m2,got_test_m2,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,175000.0,175060.0,75000.0,75380.0,0.0,0.0,1766,761,0,115204,0,0,103,50,0
Wet Nature,91000.0,26500.0,39000.0,39511.0,0.0,0.0,265,400,0,334,0,0,56,6,0
Open water,21000.0,22400.0,9000.0,11900.0,0.0,0.0,224,119,0,2440,0,0,13,5,0

In [99]:
# Saving the training and validation idx dfs
idx__WD3_plusOW_p80_tmp2_training_ML_at1__gelderland__df.to_pickle(
    idx__WD3_plusOW_p80_tmp2_training_ML_at1__gelderland__df_path
)
idx__WD3_plusOW_p80_tmp2_validation_ML_at1__gelderland__df.to_pickle(
    idx__WD3_plusOW_p80_tmp2_validation_ML_at1__gelderland__df_path
)

In [100]:
# --- WD3 ML at1 Training gpkgs --- #
training_pixels__WD3_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf = idx_df_to_gdf_func(
    idx_df=idx__WD3_plusOW_p80_tmp2_training_ML_at1__gelderland__df,
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

[path, training_pixels__WD3_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gdf] = reproject_gpkg_func(
    input_data=training_pixels__WD3_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf,
    output_epsg="EPSG:32631",
    output_gpkg=training_pixels__WD3_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg_path,
    return_gdf=True,
)

# --- WD3 ML at1 Validation gpkgs --- #
validation_pixels__WD3_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf = idx_df_to_gdf_func(
    idx_df=idx__WD3_plusOW_p80_tmp2_validation_ML_at1__gelderland__df,
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

[path, validation_pixels__WD3_plusOW_p80_tmp2_at1__gelderland__UTM32631__gdf] = reproject_gpkg_func(
    input_data=validation_pixels__WD3_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf,
    output_epsg="EPSG:32631",
    output_gpkg=validation_pixels__WD3_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg_path,
    return_gdf=True,
)

### WD4 - ML split

_attempt 1_

In [101]:
train_val__WD4_plusOW_p80_tmp2_ML_at1__gelderland__list = training_validation_split_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD4_plusOW_p80__selected__gelderland__tmp2__df,
    year_cols=idx__WD4_plusOW_p80__selected__gelderland__tmp2__df.columns,
    train_years=["2017"],
    val_years=["2018", "2019", "2020", "2021", "2022", "2023", "2024"],
    cap_pixels_by_class=WD4_at1_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    seed=42,
    area_col="bedekkingsOppervlakte1",
    pixel_area_m2=100.0,
)

idx__WD4_plusOW_p80_tmp2_training_ML_at1__gelderland__df = train_val__WD4_plusOW_p80_tmp2_ML_at1__gelderland__list[0]
idx__WD4_plusOW_p80_tmp2_validation_ML_at1__gelderland__df = train_val__WD4_plusOW_p80_tmp2_ML_at1__gelderland__list[1]
idx__WD4_plusOW_p80_tmp2_test_ML_at1__gelderland__df = train_val__WD4_plusOW_p80_tmp2_ML_at1__gelderland__list[2]
idx__WD4_plusOW_p80_tmp2_leftover_ML_at1__gelderland__df = train_val__WD4_plusOW_p80_tmp2_ML_at1__gelderland__list[3]
idx__WD4_plusOW_p80_tmp2_summary_ML_at1__gelderland__df = train_val__WD4_plusOW_p80_tmp2_ML_at1__gelderland__list[4]

In [102]:
idx__WD4_plusOW_p80_tmp2_summary_ML_at1__gelderland__df

,target_train_m2,got_train_m2,target_val_m2,got_val_m2,target_test_m2,got_test_m2,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,87500.0,88600.0,37500.0,37500.0,0.0,0.0,887,375,0,117981,0,0,57,24,0
Semi-Wet Nature,35000.0,21500.0,15000.0,15180.0,0.0,0.0,215,154,0,414,0,0,26,4,0
Wet Nature,17500.0,5000.0,7500.0,7555.0,0.0,0.0,50,76,0,64,0,0,10,2,0
Open water,21000.0,22700.0,9000.0,9000.0,0.0,0.0,227,90,0,3504,0,0,12,4,0

In [103]:
# Saving the training and validation idx dfs
idx__WD4_plusOW_p80_tmp2_training_ML_at1__gelderland__df.to_pickle(
    idx__WD4_plusOW_p80_tmp2_training_ML_at1__gelderland__df_path
)
idx__WD4_plusOW_p80_tmp2_validation_ML_at1__gelderland__df.to_pickle(
    idx__WD4_plusOW_p80_tmp2_validation_ML_at1__gelderland__df_path
)

In [104]:
# --- WD4 ML at1 Training gpkgs --- #
training_pixels__WD4_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf = idx_df_to_gdf_func(
    idx_df=idx__WD4_plusOW_p80_tmp2_training_ML_at1__gelderland__df,
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

[path, training_pixels__WD4_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gdf] = reproject_gpkg_func(
    input_data=training_pixels__WD4_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf,
    output_epsg="EPSG:32631",
    output_gpkg=training_pixels__WD4_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg_path,
    return_gdf=True,
)

# --- WD4 ML at1 Validation gpkgs --- #
validation_pixels__WD4_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf = idx_df_to_gdf_func(
    idx_df=idx__WD4_plusOW_p80_tmp2_validation_ML_at1__gelderland__df,
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

[path, validation_pixels__WD4_plusOW_p80_tmp2_at1__gelderland__UTM32631__gdf] = reproject_gpkg_func(
    input_data=validation_pixels__WD4_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf,
    output_epsg="EPSG:32631",
    output_gpkg=validation_pixels__WD4_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg_path,
    return_gdf=True,
)

### WD5 - ML split

_attempt 1_

In [105]:
train_val__WD5_plusOW_p80_tmp2_ML_at1__gelderland__list = training_validation_split_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD5_plusOW_p80__selected__gelderland__tmp2__df,
    year_cols=idx__WD5_plusOW_p80__selected__gelderland__tmp2__df.columns,
    train_years=["2017"],
    val_years=["2018", "2019", "2020", "2021", "2022", "2023", "2024"],
    cap_pixels_by_class=WD5_at1_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    seed=42,
    area_col="bedekkingsOppervlakte1",
    pixel_area_m2=100.0,
)

idx__WD5_plusOW_p80_tmp2_training_ML_at1__gelderland__df = train_val__WD5_plusOW_p80_tmp2_ML_at1__gelderland__list[0]
idx__WD5_plusOW_p80_tmp2_validation_ML_at1__gelderland__df = train_val__WD5_plusOW_p80_tmp2_ML_at1__gelderland__list[1]
idx__WD5_plusOW_p80_tmp2_test_ML_at1__gelderland__df = train_val__WD5_plusOW_p80_tmp2_ML_at1__gelderland__list[2]
idx__WD5_plusOW_p80_tmp2_leftover_ML_at1__gelderland__df = train_val__WD5_plusOW_p80_tmp2_ML_at1__gelderland__list[3]
idx__WD5_plusOW_p80_tmp2_summary_ML_at1__gelderland__df = train_val__WD5_plusOW_p80_tmp2_ML_at1__gelderland__list[4]

In [106]:
idx__WD5_plusOW_p80_tmp2_summary_ML_at1__gelderland__df

,target_train_m2,got_train_m2,target_val_m2,got_val_m2,target_test_m2,got_test_m2,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,87500.0,88600.0,37500.0,37500.0,0.0,0.0,887,375,0,117981,0,0,57,24,0
Semi-Wet Nature,35000.0,21500.0,15000.0,15180.0,0.0,0.0,215,154,0,414,0,0,26,4,0
Open water,21000.0,22200.0,9000.0,10300.0,0.0,0.0,222,103,0,2332,0,0,14,5,0

In [107]:
# Saving the training and validation idx dfs
idx__WD5_plusOW_p80_tmp2_training_ML_at1__gelderland__df.to_pickle(
    idx__WD5_plusOW_p80_tmp2_training_ML_at1__gelderland__df_path
)
idx__WD5_plusOW_p80_tmp2_validation_ML_at1__gelderland__df.to_pickle(
    idx__WD5_plusOW_p80_tmp2_validation_ML_at1__gelderland__df_path
)

In [108]:
# --- WD5 ML at1 Training gpkgs --- #
training_pixels__WD5_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf = idx_df_to_gdf_func(
    idx_df=idx__WD5_plusOW_p80_tmp2_training_ML_at1__gelderland__df,
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

[path, training_pixels__WD5_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gdf] = reproject_gpkg_func(
    input_data=training_pixels__WD5_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf,
    output_epsg="EPSG:32631",
    output_gpkg=training_pixels__WD5_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg_path,
    return_gdf=True,
)

# --- WD5 ML at1 Validation gpkgs --- #
validation_pixels__WD5_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf = idx_df_to_gdf_func(
    idx_df=idx__WD5_plusOW_p80_tmp2_validation_ML_at1__gelderland__df,
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

[path, validation_pixels__WD5_plusOW_p80_tmp2_at1__gelderland__UTM32631__gdf] = reproject_gpkg_func(
    input_data=validation_pixels__WD5_plusOW_p80_tmp2_ML_at1__gelderland__RD__gdf,
    output_epsg="EPSG:32631",
    output_gpkg=validation_pixels__WD5_plusOW_p80_tmp2_ML_at1__gelderland__UTM32631__gpkg_path,
    return_gdf=True,
)

End of the Notebook