## Importing functions

In [ ]:
from pathlib import Path
import sys

sys.path.insert(0, str(Path.cwd().resolve()))
from functions._00_common_funcs import (
    batch_func,
    check_directories_func,
    path_func,
    check_gpkg_layers_func,
    import_gpkg_func,
    import_xlsx_func,
    print_raster_info,
    import_raster_func,
    quick_rstr_plot_func,
    check_processing,
    show_nameconvention_func,
)

from functions._02_building_idx_df_funcs import (
    tmp_0_idx_df_func,
    HT_idx_df_func,
    FC_idx_df_func,
    WD_idx_df_func,
)

from functions._03_visualizing_pixel_count_funcs import (
    pixel_count_df_func,
    pixel_vis_func
)

from functions.training_validation_split_funcs import (
    cut_gdf_to_raster_pixels,
    build_gpkg_from_idx_df_func,
)

from functions._07_full_processing_nb_funcs import (
    tmp2_idx_df_func,
    clean_and_update_inspected_GPKG,
    idx_per_row_area_func,
    training_validation_split_func,
    idx_to_training_validation_gdf_func,
)

## Setting Notebook directory

In [2]:
notebook_dir = Path.cwd()

check_directories_func(notebook_dir)

'Functions, Dependencies, and Output directories found'

## Importing packages

In [3]:
import pandas as pd

## Import reference DFs

In [ ]:
from paths._00_file_paths import (
    # --- Selection reference dfs ---
    habitat_reference__HB__df_path,
    habitat_reference__s1__df_path,
)

In [5]:
# --- Selection reference dfs ---
habitat_reference__HB__df = pd.read_pickle(habitat_reference__HB__df_path)
habitat_reference__s1__df = pd.read_pickle(habitat_reference__s1__df_path)

In [102]:
habitat_reference__HB__df

,habitatnaam_disp,habitat_color,WD_division,WD_color,WD1_division,WD1_color,WD2_division,WD2_color,WD3_division,WD3_color,WD4_division,WD4_color
habitatType,,,,,,,,,,,,
H0000,Geen habitattype,#999999,No-Habitat,#aaaaaa,Remaining,#f54949,Remaining,#f54949,No-Habitat,#aaaaaa,No-Habitat,#aaaaaa
H2310,Stuifzandheiden met struikhei,#fff7b2,Dry Nature,#ffff99,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949
H2320,Binnenlandse kraaheibegroeiingen,#8c564b,Dry Nature,#ffff99,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949
H2330,Zandverstuivingen,#e8d6c3,Dry Nature,#ffff99,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949
H3130,Zwakgebufferde vennen,#9ed6f8,Wet Nature,#0c82d1,Wet Nature,#0c82d1,Wet Nature,#0c82d1,Wet Nature,#0c82d1,Wet Nature,#0c82d1
H3150,Meren krabbenscheer & fonteinkruiden,#00375f,Open water,#003f69,Open Water,NaN,Open Water,NaN,Open Water,NaN,Open Water,NaN
H3160,Zure vennen,#2e86c1,Wet Nature,#0c82d1,Wet Nature,#0c82d1,Wet Nature,#0c82d1,Wet Nature,#0c82d1,Wet Nature,#0c82d1
H3260A,Beken & rivieren met waterplanten,#0c5a92,Open water,#003f69,Open Water,NaN,Open Water,NaN,Open Water,NaN,Open Water,NaN
H3260B,Beken & rivieren met waterplanten,#0c5a92,Open water,#003f69,Open Water,NaN,Open Water,NaN,Open Water,NaN,Open Water,NaN
H3270,slikkige rivieroevers,#9b4f12,Semi-Wet Nature,#4ae4e9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H4010A,Vochtige heiden,#a1d99b,Semi-Wet Nature,#4ae4e9,Wet Nature,#0c82d1,Semi-Wet Nature,#4ae4e9,Wet Nature,#0c82d1,Semi-Wet Nature,#4ae4e9
H4030,Droge heiden,#6ba368,Dry Nature,#ffff99,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949
H5130,Jeneverbesstruwelen,#9467bd,Dry Nature,#ffff99,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949
H6120,Stroomdalgraslanden,#dbc33b,Dry Nature,#ffff99,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949
H6230,Heischrale graslanden,#d6e642,Dry Nature,#ffff99,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949
H6410,Blauwgraslanden,#e377c2,Wet Nature,#0c82d1,Wet Nature,#0c82d1,Semi-Wet Nature,#4ae4e9,Wet Nature,#0c82d1,Semi-Wet Nature,#4ae4e9
H6430A,moerasspirea,#0c5a92,Semi-Wet Nature,#4ae4e9,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949
H6430B,Ruigten en zomen (harig wilgenroosje),#0c5a92,Semi-Wet Nature,#4ae4e9,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949
H6430C,Droge bosranden,#6a9775,Dry Nature,#ffff99,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949
H6510A,Glanshaver,#aabb6e,Dry Nature,#ffff99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H6510B,Grote Vossenstaart,#aabb6e,Semi-Wet Nature,#4ae4e9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H7110A,Actieve hoogvenen (hoogveenlandschap),#329e32,Wet Nature,#0c82d1,Wet Nature,#0c82d1,Semi-Wet Nature,#4ae4e9,Wet Nature,#0c82d1,Semi-Wet Nature,#4ae4e9
H7110B,Actieve hoogvenen (heideveentjes),#329e32,Wet Nature,#0c82d1,Wet Nature,#0c82d1,Semi-Wet Nature,#4ae4e9,Wet Nature,#0c82d1,Semi-Wet Nature,#4ae4e9
H7120,Herstellend hoogveen,#4cd64c,Wet Nature,#0c82d1,Wet Nature,#0c82d1,Semi-Wet Nature,#4ae4e9,Wet Nature,#0c82d1,Semi-Wet Nature,#4ae4e9
H7140A,Overgangs- & trilven,#40cfc1,Wet Nature,#0c82d1,Wet Nature,#0c82d1,Wet Nature,#0c82d1,Wet Nature,#0c82d1,Wet Nature,#0c82d1
H7150,Pionierveg met snavelbies,#ffd59a,Semi-Wet Nature,#4ae4e9,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949
H7210,Galigaanmoerassen,#0c5a92,Open water,#003f69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H7230,Kalkmoerassen,#ffb347,Wet Nature,#0c82d1,Wet Nature,#0c82d1,Semi-Wet Nature,#4ae4e9,Wet Nature,#0c82d1,Semi-Wet Nature,#4ae4e9
H9120,Beuken-eikenbossen,#cb8d6a,Dry Nature,#ffff99,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949
H9160A,Eiken-haagbeukenbossen,#41bd5e,Semi-Wet Nature,#4ae4e9,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949
H9190,Oude eikenbossen,#cb8d6a,Dry Nature,#ffff99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H91D0,Hoogveenbossen,#266d36,Semi-Wet Nature,#4ae4e9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H91E0A,Vochtige alluviale bossen zachthoutooi,#aec7e8,Semi-Wet Nature,#4ae4e9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H91E0B,Vochtige alluviale bossen essen-iep,#aec7e8,Semi-Wet Nature,#4ae4e9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H91E0C,Vochtige alluviale bossen beenbreek,#aec7e8,Semi-Wet Nature,#4ae4e9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H91F0,Droge hardhoutooibossen,#bcbd22,Dry Nature,#ffff99,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949
LGN_OW,Open water,#0c5a92,Open water,#003f69,Open water,#003f69,Open water,#003f69,Open water,#003f69,Open water,#003f69

## Clip the processed GDF to the sentinel raster and save

_If you already have a pixeled version of the GPKG, then skip this step_

#### Setting dir

In [7]:
# # Setting dir
# from functions._00_file_paths import (
#     # --- Habitat kart Processed GPKGs ---
#     OW_all_years__selected__lgn__RD__gpkg_path,

#     # --- sentinel 2 basisraster ---
#     s2_basisraster__10m__RD__rstr_path,
#     s2_basisraster__20m__RD__rstr_path,

#     # --- pixeled gdfs --- 
#     OW_all_years__selected_pixeled__lgn__RD__gpkg_path,
# )

In [8]:
# # --- Habitat kart Processed GPKGs ---
# # Gelderland 
# habitat_kart__processed__gelderland__RD__gdf = import_gpkg_func(
#     gdf_path=habitat_kart__processed__gelderland__RD__gpkg_path, 
#     layer='habitat_kart__processed__gelderland__RD__layer', 
#     index_col='index'
# )

# # Website plus hr 
# habitat_kart__processed__website_plusHR__RD__gdf = import_gpkg_func(
#     gdf_path=habitat_kart__processed__website_plusHR__RD__gpkg_path,
#     layer='habitat_kart__processed__website_plusHR__RD__layer',
#     index_col='index'
# )
# 
# # All years OW
# OW_all_years__selected__lgn__RD__gdf = import_gpkg_func(
#     gdf_path=OW_all_years__selected__lgn__RD__gpkg_path, 
#     layer='OW_all_years__selected__lgn__RD__layer', 
#     index_col='index'
# )

In [ ]:
# # Clip to raster -> very time consuming!
# OW_all_years__selected_pixeled__lgn__RD__gdf = cut_gdf_to_raster_pixels(
#     gdf=OW_all_years__selected__lgn__RD__gdf,
#     raster_path=s2_basisraster__10m__RD__rstr_path,
#     all_touched=True,
#     make_geoms_valid=True,
#     progress=True,
# )

In [10]:
# # Save directly to file
# OW_all_years__selected_pixeled__lgn__RD__gdf.to_file(
#     filename=OW_all_years__selected_pixeled__lgn__RD__gpkg_path,
#     layer="OW_all_years__selected_pixeled__lgn__RD__layer",
#     driver="GPKG"
# )

## Building (pixeled) IDX table for new selection

#### _Setting dir_

In [11]:
# Setting dir
from functions._00_file_paths import (
    # --- (pixeled) gdfs --- 
    habitat_kart__processed__gelderland__RD__gpkg_path,
    habitat_kart__processed__website_plusHR__RD__gpkg_path,
    habitat_kart__pixeled__gelderland__RD__gpkg_path,
    habitat_kart__pixeled__website_plusHR__RD__gpkg_path,

    # --- Create new pixeled idx dfs ---
    # HB tmp2
    idx__HB__division__gelderland__tmp2__df_path,
    idx__HB__division__website_plusHR__tmp2__df_path,
    idx__HB__pixeled__gelderland__tmp2__df_path,
    idx__HB__pixeled__website_plusHR__tmp2__df_path,
    # FC_p80 tmp2
    idx__FC_p80__division__gelderland__tmp2__df_path,
    idx__FC_p80__division__website_plusHR__tmp2__df_path,
    idx__FC_p80__pixeled__gelderland__tmp2__df_path,
    idx__FC_p80__pixeled__website_plusHR__tmp2__df_path,
    # WD_p80 tmp2
    idx__WD1_p80__division__gelderland__tmp2__df_path,
    idx__WD1_p80__division__website_plusHR__tmp2__df_path,
    idx__WD2_p80__division__gelderland__tmp2__df_path,
    idx__WD2_p80__division__website_plusHR__tmp2__df_path,
    
    idx__WD1_p80__pixeled__gelderland__tmp2__df_path,
    idx__WD1_p80__pixeled__website_plusHR__tmp2__df_path,
    idx__WD2_p80__pixeled__gelderland__tmp2__df_path,
    idx__WD2_p80__pixeled__website_plusHR__tmp2__df_path,
)

#### _Loading the GDFs_

In [12]:
# # Loading the processed GDF
# # Gelderland 
# habitat_kart__processed__gelderland__RD__gdf = import_gpkg_func(
#     gdf_path=habitat_kart__processed__gelderland__RD__gpkg_path, 
#     layer='habitat_kart__processed__gelderland__RD__layer', 
#     index_col='index'
# )

# # Website plus hr 
# habitat_kart__processed__website_plusHR__RD__gdf = import_gpkg_func(
#     gdf_path=habitat_kart__processed__website_plusHR__RD__gpkg_path,
#     layer='habitat_kart__processed__website_plusHR__RD__layer',
#     index_col='index'
# )

In [13]:
# # Loading the pixeled GDF
# # Gelderland 
# habitat_kart__pixeled__gelderland__RD__gdf = import_gpkg_func(
#     gdf_path=habitat_kart__pixeled__gelderland__RD__gpkg_path, 
#     layer='habitat_kart__pixeled__gelderland__RD__layer', 
#     index_col='new_index'
# )

# # Website plus hr 
# habitat_kart__pixeled__website_plusHR__RD__gdf = import_gpkg_func(
#     gdf_path=habitat_kart__pixeled__website_plusHR__RD__gpkg_path,
#     layer='habitat_kart__pixeled__website_plusHR__RD__layer',
#     index_col='new_index'
# )

In [14]:
# habitat_kart__pixeled__website_plusHR__RD__gdf.head()

#### _Loading the IDX dfs (if available)_

In [ ]:
# idx__HB__division__gelderland__tmp2__df = pd.read_pickle(idx__HB__division__gelderland__tmp2__df_path)
# idx__HB__division__website_plusHR__tmp2__df = pd.read_pickle(idx__HB__division__website_plusHR__tmp2__df_path)
# idx__HB__pixeled__gelderland__tmp2__df = pd.read_pickle(idx__HB__pixeled__gelderland__tmp2__df_path)
# idx__HB__pixeled__website_plusHR__tmp2__df = pd.read_pickle(idx__HB__pixeled__website_plusHR__tmp2__df_path)

#### _Using AO tmp0, any new combination can be made_

In [16]:
# # AO tmp2 idx df (tmp2 = 2017-> 2024 ONLY)
# idx__AO__pixeled__gelderland__tmp2__df, idx__AO__pixeled__gelderland__tmp2__count = tmp2_idx_df_func(
#     gdf=habitat_kart__pixeled__gelderland__RD__gdf,
#     group_col='habitatnaam_1_disp',
#     year_col='years',
# )
# idx__AO__pixeled__website_plusHR__tmp2__df, idx__AO__pixeled__website_plusHR__tmp2__count = tmp2_idx_df_func(
#     gdf=habitat_kart__pixeled__website_plusHR__RD__gdf,
#     group_col='habitatnaam_1_disp',
#     year_col='years',
# )

In [17]:
# idx__AO__pixeled__gelderland__tmp2__df.head()

In [18]:
# # save
# idx__AO__pixeled__gelderland__tmp2__df.to_pickle(idx__AO__pixeled__gelderland__tmp2__df_path)
# idx__AO__pixeled__website_plusHR__tmp2__df.to_pickle(idx__AO__pixeled__website_plusHR__tmp2__df_path)

#### _Using HT func only the rows with a true Habitat type are selected_

In [19]:
# # HB tmp2 idx df
# idx__HB__pixeled__gelderland__tmp2__df, idx__HB__pixeled__gelderland__tmp2__count = HT_idx_df_func(
#     gdf=habitat_kart__pixeled__gelderland__RD__gdf,
#     idx_df=idx__AO__pixeled__gelderland__tmp2__df,
#     habitat_types_df=habitat_reference__HB__df,
#     habitat_col='habitatType1'
# )

# idx__HB__pixeled__website_plusHR__tmp2__df, idx__HB__pixeled__website_plusHR__tmp2__count = HT_idx_df_func(
#     gdf=habitat_kart__pixeled__website_plusHR__RD__gdf,
#     idx_df=idx__AO__pixeled__website_plusHR__tmp2__df,
#     habitat_types_df=habitat_reference__HB__df,
#     habitat_col='habitatType1'
# )

In [20]:
# # save
# idx__HB__pixeled__gelderland__tmp2__df.to_pickle(idx__HB__pixeled__gelderland__tmp2__df_path)
# idx__HB__pixeled__website_plusHR__tmp2__df.to_pickle(idx__HB__pixeled__website_plusHR__tmp2__df_path)

#### _Using FC func only the habitat covers above a percentage are selected_

In [21]:
# # FC tmp2 idx df
# idx__FC_p80__division__gelderland__tmp2__df, idx__FC_p80__division__gelderland__tmp2__count = FC_idx_df_func(
#     gdf=habitat_kart__processed__gelderland__RD__gdf,
#     idx_df=idx__HB__division__gelderland__tmp2__df,
#     min_percentage=80,
# )

# idx__FC_p80__division__website_plusHR__tmp2__df, idx__FC_p80__division__website_plusHR__tmp2__count = FC_idx_df_func(
#     gdf=habitat_kart__processed__website_plusHR__RD__gdf,
#     idx_df=idx__HB__division__website_plusHR__tmp2__df,
#     min_percentage=80,
# )

In [22]:
# # # Save
# idx__FC_p80__division__gelderland__tmp2__df.to_pickle(idx__FC_p80__division__gelderland__tmp2__df_path)
# idx__FC_p80__division__website_plusHR__tmp2__df.to_pickle(idx__FC_p80__division__website_plusHR__tmp2__df_path)

In [23]:
# # FC tmp2 idx df
# idx__FC_p80__pixeled__gelderland__tmp2__df, idx__FC_p80__pixeled__gelderland__tmp2__count = FC_idx_df_func(
#     gdf=habitat_kart__pixeled__gelderland__RD__gdf,
#     idx_df=idx__HB__pixeled__gelderland__tmp2__df,
#     min_percentage=80,
# )

# idx__FC_p80__pixeled__website_plusHR__tmp2__df, idx__FC__pixeled__website_plusHR__tmp2__count = FC_idx_df_func(
#     gdf=habitat_kart__pixeled__website_plusHR__RD__gdf,
#     idx_df=idx__HB__pixeled__website_plusHR__tmp2__df,
#     min_percentage=80,
# )

In [24]:
# # # Save
# idx__FC_p80__pixeled__gelderland__tmp2__df.to_pickle(idx__FC_p80__pixeled__gelderland__tmp2__df_path)
# idx__FC_p80__pixeled__website_plusHR__tmp2__df.to_pickle(idx__FC_p80__pixeled__website_plusHR__tmp2__df_path)

#### _Using WD func only habitats are grouped based on WD_

In [25]:
# # WD tmp2 idx df
# idx__WD1_p80__pixeled__gelderland__tmp2__df, idx__WD1_p80__pixeled__gelderland__tmp2__count = WD_idx_df_func(
#     gdf=habitat_kart__pixeled__gelderland__RD__gdf,
#     idx_df=idx__FC_p80__pixeled__gelderland__tmp2__df,
#     habitat_types_df=habitat_reference__HB__df,
#     habitat_col='habitatType1',
#     wd_col='WD1_division'
# )

# idx__WD1_p80__pixeled__website_plusHR__tmp2__df, idx__WD1_p80__pixeled__website_plusHR__tmp2__count = WD_idx_df_func(
#     gdf=habitat_kart__pixeled__website_plusHR__RD__gdf,
#     idx_df=idx__FC_p80__pixeled__website_plusHR__tmp2__df,
#     habitat_types_df=habitat_reference__HB__df,
#     habitat_col='habitatType1',
#     wd_col='WD1_division'
# )

# # WD tmp2 idx df
# idx__WD2_p80__pixeled__gelderland__tmp2__df, idx__WD2_p80__pixeled__gelderland__tmp2__count = WD_idx_df_func(
#     gdf=habitat_kart__pixeled__gelderland__RD__gdf,
#     idx_df=idx__FC_p80__pixeled__gelderland__tmp2__df,
#     habitat_types_df=habitat_reference__HB__df,
#     habitat_col='habitatType1',
#     wd_col='WD2_division'
# )

# idx__WD2_p80__pixeled__website_plusHR__tmp2__df, idx__WD2_p80__pixeled__website_plusHR__tmp2__count = WD_idx_df_func(
#     gdf=habitat_kart__pixeled__website_plusHR__RD__gdf,
#     idx_df=idx__FC_p80__pixeled__website_plusHR__tmp2__df,
#     habitat_types_df=habitat_reference__HB__df,
#     habitat_col='habitatType1',
#     wd_col='WD2_division'
# )

In [26]:
# # save
# idx__WD1_p80__pixeled__gelderland__tmp2__df.to_pickle(idx__WD1_p80__pixeled__gelderland__tmp2__df_path)
# idx__WD1_p80__pixeled__website_plusHR__tmp2__df.to_pickle(idx__WD1_p80__pixeled__website_plusHR__tmp2__df_path)
# idx__WD2_p80__pixeled__gelderland__tmp2__df.to_pickle(idx__WD2_p80__pixeled__gelderland__tmp2__df_path)
# idx__WD2_p80__pixeled__website_plusHR__tmp2__df.to_pickle(idx__WD2_p80__pixeled__website_plusHR__tmp2__df_path)

In [27]:
# # WD tmp2 idx df
# idx__WD1_p80__division__gelderland__tmp2__df, idx__WD1_p80__division__gelderland__tmp2__count = WD_idx_df_func(
#     gdf=habitat_kart__processed__gelderland__RD__gdf,
#     idx_df=idx__FC_p80__division__gelderland__tmp2__df,
#     habitat_types_df=habitat_reference__HB__df,
#     habitat_col='habitatType1',
#     wd_col='WD1_division'
# )

# idx__WD1_p80__division__website_plusHR__tmp2__df, idx__WD1_p80__division__website_plusHR__tmp2__count = WD_idx_df_func(
#     gdf=habitat_kart__processed__website_plusHR__RD__gdf,
#     idx_df=idx__FC_p80__division__website_plusHR__tmp2__df,
#     habitat_types_df=habitat_reference__HB__df,
#     habitat_col='habitatType1',
#     wd_col='WD1_division'
# )

# # WD tmp2 idx df
# idx__WD2_p80__division__gelderland__tmp2__df, idx__WD2_p80__division__gelderland__tmp2__count = WD_idx_df_func(
#     gdf=habitat_kart__processed__gelderland__RD__gdf,
#     idx_df=idx__FC_p80__division__gelderland__tmp2__df,
#     habitat_types_df=habitat_reference__HB__df,
#     habitat_col='habitatType1',
#     wd_col='WD2_division'
# )

# idx__WD2_p80__division__website_plusHR__tmp2__df, idx__WD2_p80__division__website_plusHR__tmp2__count = WD_idx_df_func(
#     gdf=habitat_kart__processed__website_plusHR__RD__gdf,
#     idx_df=idx__FC_p80__division__website_plusHR__tmp2__df,
#     habitat_types_df=habitat_reference__HB__df,
#     habitat_col='habitatType1',
#     wd_col='WD2_division'
# )

In [28]:
# # save
# idx__WD1_p80__division__gelderland__tmp2__df.to_pickle(idx__WD1_p80__division__gelderland__tmp2__df_path)
# idx__WD1_p80__division__website_plusHR__tmp2__df.to_pickle(idx__WD1_p80__division__website_plusHR__tmp2__df_path)
# idx__WD2_p80__division__gelderland__tmp2__df.to_pickle(idx__WD2_p80__division__gelderland__tmp2__df_path)
# idx__WD2_p80__division__website_plusHR__tmp2__df.to_pickle(idx__WD2_p80__division__website_plusHR__tmp2__df_path)

#### _s1 selection func_

In [29]:
# # S1 tmp1 idx dfs
# idx__s1__pixeled__gelderland__tmp2__df, idx__s1__pixeled__gelderland__tmp2__count = HT_idx_df_func(
#     gdf=habitat_kart__pixeled__gelderland__RD__gdf,
#     idx_df=idx__FC__pixeled__gelderland__tmp2__df,
#     habitat_types_df=habitat_reference__s1__df,
#     habitat_col='habitatType1'
# )

# idx__s1__pixeled__website_plusHR__tmp2__df, idx__s1__pixeled__website_plusHR__tmp2__count = HT_idx_df_func(
#     gdf=habitat_kart__pixeled__website_plusHR__RD__gdf,
#     idx_df=idx__FC__pixeled__website_plusHR__tmp2__df,
#     habitat_types_df=habitat_reference__s1__df,
#     habitat_col='habitatType1'
# )

In [30]:
# # save
# idx__s1__pixeled__gelderland__tmp2__df.to_pickle(idx__s1__pixeled__gelderland__tmp2__df_path)
# idx__s1__pixeled__website_plusHR__tmp2__df.to_pickle(idx__s1__pixeled__website_plusHR__tmp2__df_path)

## Visualizing pixel count (before inspection)

In [31]:
# ## rounding the areacover column off 
# # Gelderland
# habitat_kart__pixeled__gelderland__RD__gdf["bedekkingsOppervlakte1"] = (
#     habitat_kart__pixeled__gelderland__RD__gdf["bedekkingsOppervlakte1"].round().astype("Int64")
# )

# # Website plusHR
# habitat_kart__pixeled__website_plusHR__RD__gdf["bedekkingsOppervlakte1"] = (
#     habitat_kart__pixeled__website_plusHR__RD__gdf["bedekkingsOppervlakte1"].round().astype("Int64")
# )

In [32]:
# # Estimating the pixel count
# # WD
# pixel_count__WD__pixeled__gelderland__tmp2__df, pixel_count__WD__pixeled__gelderland__tmp2__check = pixel_count_df_func(
#     gdf=habitat_kart__pixeled__gelderland__RD__gdf,
#     idx_df=idx__WD__pixeled__gelderland__tmp2__df,
# )

# pixel_count__WD__pixeled__website_plusHR__tmp2__df, pixel_count__WD__pixeled__website_plusHR__tmp2__check = pixel_count_df_func(
#     gdf=habitat_kart__pixeled__website_plusHR__RD__gdf,
#     idx_df=idx__WD__pixeled__website_plusHR__tmp2__df,
# )

# # s1
# pixel_count__s1__pixeled__gelderland__tmp2__df, pixel_count__s1__pixeled__gelderland__tmp2__check = pixel_count_df_func(
#     gdf=habitat_kart__pixeled__gelderland__RD__gdf,
#     idx_df=idx__s1__pixeled__gelderland__tmp2__df,
# )

# pixel_count__s1__pixeled__website_plusHR__tmp2__df, pixel_count__s1__pixeled__website_plusHR__tmp2__check = pixel_count_df_func(
#     gdf=habitat_kart__pixeled__website_plusHR__RD__gdf,
#     idx_df=idx__s1__pixeled__website_plusHR__tmp2__df,
# )

In [33]:
# # making the year cols for visualization
# tmp_2_gelderland_years = pixel_count__WD__pixeled__gelderland__tmp2__df.columns.tolist()
# tmp_2_website_plusHR_years = pixel_count__WD__pixeled__website_plusHR__tmp2__df.columns.tolist()

In [34]:
# pixel_vis_func(
#     df=pixel_count__WD__pixeled__gelderland__tmp2__df, 
#     years=tmp_2_gelderland_years, 
#     title="WD tmp2 Gelderland Pixels per Year"
# )

In [35]:
# pixel_vis_func(
#     df=pixel_count__WD__pixeled__website_plusHR__tmp2__df, 
#     years=tmp_2_website_plusHR_years, 
#     title="WD tmp2 Website_plusHR Pixels per Year"
# )

In [36]:
# pixel_vis_func(
#     df=pixel_count__s1__pixeled__gelderland__tmp2__df, 
#     years=tmp_2_gelderland_years, 
#     title="s1 tmp2 Gelderland Pixels per Year"
# )

In [37]:
# pixel_vis_func(
#     df=pixel_count__s1__pixeled__website_plusHR__tmp2__df, 
#     years=tmp_2_website_plusHR_years, 
#     title="s1 tmp2 Website_plusHR Pixels per Year"
# )

## QGIS inspection export

#### Setting dir

In [38]:
# Setting dir
from functions._00_file_paths import (
    # --- (pixeled) gdfs --- 
    habitat_kart__processed__gelderland__RD__gpkg_path,
    habitat_kart__processed__website_plusHR__RD__gpkg_path,
    habitat_kart__pixeled__gelderland__RD__gpkg_path,
    habitat_kart__pixeled__website_plusHR__RD__gpkg_path,


    # --- (pixeled) idx dfs ---
    # FC_p80 tmp2
    idx__FC_p80__division__gelderland__tmp2__df_path,
    idx__FC_p80__division__website_plusHR__tmp2__df_path,
    idx__FC_p80__pixeled__gelderland__tmp2__df_path,
    idx__FC_p80__pixeled__website_plusHR__tmp2__df_path,
    # WD_p80 tmp2
    idx__WD1_p80__division__gelderland__tmp2__df_path,
    idx__WD1_p80__division__website_plusHR__tmp2__df_path,
    idx__WD2_p80__division__gelderland__tmp2__df_path,
    idx__WD2_p80__division__website_plusHR__tmp2__df_path,
    
    idx__WD1_p80__pixeled__gelderland__tmp2__df_path,
    idx__WD1_p80__pixeled__website_plusHR__tmp2__df_path,
    idx__WD2_p80__pixeled__gelderland__tmp2__df_path,
    idx__WD2_p80__pixeled__website_plusHR__tmp2__df_path,


    # --- Habitat kart idx-picked pixels GPKGs (for inspection) ---
    habitat_kart__FC_p80_tmp2_polys__gelderland__RD__gpkg_path,
    habitat_kart__FC_p80_tmp2_polys__website_plusHR__RD__gpkg_path,
    habitat_kart__FC_p80_tmp2_inspection__gelderland__RD__gpkg_path,
    habitat_kart__FC_p80_tmp2_inspection__website_plusHR__RD__gpkg_path,

    habitat_kart__WD1_p80_tmp2_polys__gelderland__RD__gpkg_path,
    habitat_kart__WD1_p80_tmp2_polys__website_plusHR__RD__gpkg_path,
    habitat_kart__WD2_p80_tmp2_polys__gelderland__RD__gpkg_path,
    habitat_kart__WD2_p80_tmp2_polys__website_plusHR__RD__gpkg_path,
    
    habitat_kart__WD1_p80_tmp2_inspection__gelderland__RD__gpkg_path,
    habitat_kart__WD1_p80_tmp2_inspection__website_plusHR__RD__gpkg_path,
    habitat_kart__WD2_p80_tmp2_inspection__gelderland__RD__gpkg_path,
    habitat_kart__WD2_p80_tmp2_inspection__website_plusHR__RD__gpkg_path,
)

#### Loading the GDFs

In [39]:
# # Loading the processed GDF
# # Gelderland 
# habitat_kart__processed__gelderland__RD__gdf = import_gpkg_func(
#     gdf_path=habitat_kart__processed__gelderland__RD__gpkg_path, 
#     layer='habitat_kart__processed__gelderland__RD__layer', 
#     index_col='index'
# )

# # Website plus hr 
# habitat_kart__processed__website_plusHR__RD__gdf = import_gpkg_func(
#     gdf_path=habitat_kart__processed__website_plusHR__RD__gpkg_path,
#     layer='habitat_kart__processed__website_plusHR__RD__layer',
#     index_col='index'
# )

In [40]:
# # Loading the pixeled GDF
# # Gelderland 
# habitat_kart__pixeled__gelderland__RD__gdf = import_gpkg_func(
#     gdf_path=habitat_kart__pixeled__gelderland__RD__gpkg_path, 
#     layer='habitat_kart__pixeled__gelderland__RD__layer', 
#     index_col='new_index'
# )

# # Website plus hr 
# habitat_kart__pixeled__website_plusHR__RD__gdf = import_gpkg_func(
#     gdf_path=habitat_kart__pixeled__website_plusHR__RD__gpkg_path,
#     layer='habitat_kart__pixeled__website_plusHR__RD__layer',
#     index_col='new_index'
# )

#### _Loading the idx dfs_

In [41]:
# idx__HB__division__gelderland__tmp2__df = pd.read_pickle(idx__HB__division__gelderland__tmp2__df_path)
# idx__HB__division__website_plusHR__tmp2__df = pd.read_pickle(idx__HB__division__website_plusHR__tmp2__df_path)
# idx__FC__division__gelderland__tmp2__df = pd.read_pickle(idx__FC__division__gelderland__tmp2__df_path)
# idx__FC__division__website_plusHR__tmp2__df = pd.read_pickle(idx__FC__division__website_plusHR__tmp2__df_path)

#### _Building the selection GPKG_

In [42]:
# # FC Gelderland
# habitat_kart__FC_p80_tmp2_polys__gelderland__RD__gdf = build_gpkg_from_idx_df_func(
#     idx_df=idx__FC_p80__division__gelderland__tmp2__df,
#     source_gdf=habitat_kart__processed__gelderland__RD__gdf,
#     out_gpkg=habitat_kart__FC_p80_tmp2_polys__gelderland__RD__gpkg_path,
#     single_layer=True,
#     single_layer_name="habitat_kart__FC_p80_tmp2_polys__gelderland__RD__layer",
# )

# # FC Website_plusHR
# habitat_kart__FC_p80_tmp2_polys__website_plusHR__RD__gdf = build_gpkg_from_idx_df_func(
#     idx_df=idx__FC_p80__division__website_plusHR__tmp2__df,
#     source_gdf=habitat_kart__processed__website_plusHR__RD__gdf,
#     out_gpkg=habitat_kart__FC_p80_tmp2_polys__website_plusHR__RD__gpkg_path,
#     single_layer=True,
#     single_layer_name="habitat_kart__FC_p80_tmp2_polys__website_plusHR__RD__layer",
# )

In [43]:
# # WD Gelderland
# habitat_kart__FC_p80_tmp2_inspection__gelderland__RD__gdf = build_gpkg_from_idx_df_func(
#     idx_df=idx__FC_p80__pixeled__gelderland__tmp2__df,
#     source_gdf=habitat_kart__pixeled__gelderland__RD__gdf,
#     out_gpkg=habitat_kart__FC_p80_tmp2_inspection__gelderland__RD__gpkg_path,
#     single_layer=True,
#     single_layer_name="habitat_kart__FC_p80_tmp2_inspection__gelderland__RD__layer",
# )

# # WD Website_plusHR
# habitat_kart__FC_p80_tmp2_inspection__website_plusHR__RD__gdf = build_gpkg_from_idx_df_func(
#     idx_df=idx__FC_p80__pixeled__website_plusHR__tmp2__df,
#     source_gdf=habitat_kart__pixeled__website_plusHR__RD__gdf,
#     out_gpkg=habitat_kart__FC_p80_tmp2_inspection__website_plusHR__RD__gpkg_path,
#     single_layer=True,
#     single_layer_name="habitat_kart__FC_p80_tmp2_inspection__website_plusHR__RD__layer",
# )

## Import and check selected GPKGs

#### Setting dir

In [44]:
# Setting dir
from functions._00_file_paths import (
    # --- Selected/Inspected training validation pixels ---
    habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gpkg_path,


    # --- IDX selected dfs ---
    idx__FC_plusOW_p80__selected__gelderland__tmp2__df_path,
    idx__WD_plusOW__selected__gelderland__tmp2__df_path,
    idx__WD1_plusOW__selected__gelderland__tmp2__df_path,
    idx__WD2_plusOW__selected__gelderland__tmp2__df_path,
    idx__WD3_plusOW__selected__gelderland__tmp2__df_path,
    idx__WD4_plusOW__selected__gelderland__tmp2__df_path,
)

#### Load the selected GPKGs

In [45]:
# Loading the Selected/Inspected gdfs
# Gelderland 
habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf = import_gpkg_func(
    gdf_path=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gpkg_path, 
    layer='habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__layer', 
    index_col='index',
)

#### Load the available idx dfs

In [46]:
# idx__FC_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__FC_plusOW_p80__selected__gelderland__tmp2__df_path)

#### Update the GDF (recalculate area & cleaning)

In [47]:
# habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf = clean_and_update_inspected_GPKG(
#     habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf
# )

In [48]:
# # Save the updated GPKG
# habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf.to_file(
#     filename=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gpkg_path,
#     layer="habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__layer",
#     driver="GPKG"
# )

In [49]:
idx__FC_plusOW_p80__selected__gelderland__tmp2__df, idx__FC_plusOW_p80__selected__gelderland__tmp2__count = tmp_0_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

In [50]:
# Remove the LGN2025 column from FC_p80 idx
idx__FC_plusOW_p80__selected__gelderland__tmp2__df = idx__FC_plusOW_p80__selected__gelderland__tmp2__df.drop(columns='2025')

In [51]:
idx__FC_plusOW_p80__selected__gelderland__tmp2__df.to_pickle(idx__FC_plusOW_p80__selected__gelderland__tmp2__df_path)

#### Building new IDX dfs

In [52]:
# WD
idx__WD_plusOW__selected__gelderland__tmp2__df, idx__WD_plusOW__selected__gelderland__tmp2__count = WD_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__FC_plusOW_p80__selected__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__HB__df,
    habitat_col='habitatType1',
    wd_col='WD_division'
)

In [53]:
idx__WD_plusOW__selected__gelderland__tmp2__df.to_pickle(idx__WD_plusOW__selected__gelderland__tmp2__df_path)#

In [54]:
# WD
idx__WD1_plusOW__selected__gelderland__tmp2__df, idx__WD1_plusOW__selected__gelderland__tmp2__count = WD_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__FC_plusOW_p80__selected__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__HB__df,
    habitat_col='habitatType1',
    wd_col='WD1_division'
)

In [55]:
idx__WD1_plusOW__selected__gelderland__tmp2__df.to_pickle(idx__WD1_plusOW__selected__gelderland__tmp2__df_path)

In [56]:
# WD
idx__WD2_plusOW__selected__gelderland__tmp2__df, idx__WD2_plusOW__selected__gelderland__tmp2__count = WD_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__FC_plusOW_p80__selected__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__HB__df,
    habitat_col='habitatType1',
    wd_col='WD2_division'
)

In [57]:
idx__WD2_plusOW__selected__gelderland__tmp2__df.to_pickle(idx__WD2_plusOW__selected__gelderland__tmp2__df_path)

In [58]:
# WD
idx__WD3_plusOW__selected__gelderland__tmp2__df, idx__WD3_plusOW__selected__gelderland__tmp2__count = WD_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__FC_plusOW_p80__selected__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__HB__df,
    habitat_col='habitatType1',
    wd_col='WD3_division'
)

idx__WD3_plusOW__selected__gelderland__tmp2__df = idx__WD3_plusOW__selected__gelderland__tmp2__df.drop(index="No-Habitat")

In [59]:
idx__WD3_plusOW__selected__gelderland__tmp2__df.to_pickle(idx__WD3_plusOW__selected__gelderland__tmp2__df_path)

In [60]:
# WD
idx__WD4_plusOW__selected__gelderland__tmp2__df, idx__WD4_plusOW__selected__gelderland__tmp2__count = WD_idx_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__FC_plusOW_p80__selected__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__HB__df,
    habitat_col='habitatType1',
    wd_col='WD4_division'
)

idx__WD4_plusOW__selected__gelderland__tmp2__df = idx__WD4_plusOW__selected__gelderland__tmp2__df.drop(index="No-Habitat")

In [61]:
idx__WD4_plusOW__selected__gelderland__tmp2__df.to_pickle(idx__WD4_plusOW__selected__gelderland__tmp2__df_path)

#### Visualizing pixel count

In [62]:
years_2017_2025 = ['2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']

In [63]:
# Load the IDX dfs
idx__FC_plusOW_p80__selected__gelderland__tmp2__df = pd.read_pickle(idx__FC_plusOW_p80__selected__gelderland__tmp2__df_path)
idx__WD_plusOW__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD_plusOW__selected__gelderland__tmp2__df_path)
idx__WD1_plusOW__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD1_plusOW__selected__gelderland__tmp2__df_path)
idx__WD2_plusOW__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD2_plusOW__selected__gelderland__tmp2__df_path)
idx__WD3_plusOW__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD3_plusOW__selected__gelderland__tmp2__df_path)
idx__WD4_plusOW__selected__gelderland__tmp2__df = pd.read_pickle(idx__WD4_plusOW__selected__gelderland__tmp2__df_path)

In [64]:
idx__WD_plusOW__selected__gelderland__tmp2__area_df, idx__WD_plusOW__selected__gelderland__tmp2__count = pixel_count_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD_plusOW__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
)

pixel_vis_func(
    df=idx__WD_plusOW__selected__gelderland__tmp2__area_df, 
    years=years_2017_2025, 
    title="WD tmp2 Gelderland Pixels per Year"
)

In [65]:
idx__WD1_plusOW__selected__gelderland__tmp2__area_df, idx__WD1_plusOW__selected__gelderland__tmp2__count = pixel_count_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD1_plusOW__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
)

pixel_vis_func(
    df=idx__WD1_plusOW__selected__gelderland__tmp2__area_df, 
    years=years_2017_2025, 
    title="WD1 tmp2 Gelderland Pixels per Year"
)

In [66]:
idx__WD2_plusOW__selected__gelderland__tmp2__area_df, idx__WD2_plusOW__selected__gelderland__tmp2__count = pixel_count_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD2_plusOW__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
)

pixel_vis_func(
    df=idx__WD2_plusOW__selected__gelderland__tmp2__area_df, 
    years=years_2017_2025, 
    title="WD2 tmp2 Gelderland Pixels per Year"
)

In [67]:
idx__WD3_plusOW__selected__gelderland__tmp2__area_df, idx__WD3_plusOW__selected__gelderland__tmp2__count = pixel_count_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD3_plusOW__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
)

pixel_vis_func(
    df=idx__WD3_plusOW__selected__gelderland__tmp2__area_df, 
    years=years_2017_2025, 
    title="WD3 tmp2 Gelderland Pixels per Year"
)

In [68]:
idx__WD4_plusOW__selected__gelderland__tmp2__area_df, idx__WD4_plusOW__selected__gelderland__tmp2__count = pixel_count_df_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD4_plusOW__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
)

pixel_vis_func(
    df=idx__WD4_plusOW__selected__gelderland__tmp2__area_df, 
    years=years_2017_2025, 
    title="WD4 tmp2 Gelderland Pixels per Year"
)

## Training validation split

#### Determining the area that will go into training / validating

In [69]:
WD_area_text = idx_per_row_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD_plusOW__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
    as_text=True,
    divide_by=100
)

print("WD areas per row:\n" + WD_area_text)

WD areas per row:
Dry Nature: 128967.81 pixels
Wet Nature: 270.87 pixels
No-Habitat: 182564.00 pixels
Semi-Wet Nature: 1967.96 pixels
Open water: 1186.64 pixels

In [70]:
WD_dict = {
    "Dry Nature": 1250,
    "Wet Nature": 250,
    "No-Habitat": 1250,
    "Semi-Wet Nature": 500,
    "Open water": 250,
}

In [71]:
WD1_area_text = idx_per_row_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD1_plusOW__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
    as_text=True,
)

print("WD1 areas per row:\n" + WD1_area_text)

WD1 areas per row:
Remaining: 304963.81 pixels
Wet Nature: 1559.83 pixels
Open water: 1186.64 pixels

In [72]:
WD1_dict = {
    "Remaining": 3000,
    "Wet Nature": 1400,
    "Open water": 300,
}

In [73]:
WD2_area_text = idx_per_row_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD2_plusOW__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
    as_text=True,
)

print("WD3 areas per row:\n" + WD2_area_text)

WD3 areas per row:
Remaining: 304963.81 pixels
Semi-Wet Nature: 1296.96 pixels
Wet Nature: 262.87 pixels
Open water: 1186.64 pixels

In [74]:
WD2_dict = {
    "Remaining": 1250,
    "Wet Nature": 250,
    "Semi-Wet Nature": 500,
    "Open water": 250,
}

In [75]:
WD3_area_text = idx_per_row_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD3_plusOW__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
    as_text=True,
)

print("WD3 areas per row:\n" + WD3_area_text)

WD3 areas per row:
Remaining: 122399.81 pixels
Wet Nature: 1559.83 pixels
Open water: 1186.64 pixels

In [76]:
WD3_dict = {
    "Remaining": 2500,
    "Wet Nature": 1300,
    "Open water": 300,
}

In [77]:
WD4_area_text = idx_per_row_area_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD4_plusOW__selected__gelderland__tmp2__df,
    area_col="bedekkingsOppervlakte1",
    as_text=True,
)

print("WD4 areas per row:\n" + WD4_area_text)

WD4 areas per row:
Remaining: 122399.81 pixels
Semi-Wet Nature: 1296.96 pixels
Wet Nature: 262.87 pixels
Open water: 1186.64 pixels

In [78]:
WD4_dict = {
    "Remaining": 1250,
    "Semi-Wet Nature": 500,
    "Wet Nature": 250,
    "Open water": 300,
}

#### Splitting the data

In [79]:
# Setting dir
from functions._00_file_paths import (
    # --- IDX training/validation dfs ---
    idx__WD_plusOW_p80_tmp2_training__gelderland__df_path,
    idx__WD_plusOW_p80_tmp2_validation__gelderland__df_path,
    idx__WD1_plusOW_p80_tmp2_training__gelderland__df_path,
    idx__WD1_plusOW_p80_tmp2_validation__gelderland__df_path,
    idx__WD2_plusOW_p80_tmp2_training__gelderland__df_path,
    idx__WD2_plusOW_p80_tmp2_validation__gelderland__df_path,
    idx__WD3_plusOW_p80_tmp2_training__gelderland__df_path,
    idx__WD3_plusOW_p80_tmp2_validation__gelderland__df_path,
    idx__WD4_plusOW_p80_tmp2_training__gelderland__df_path,
    idx__WD4_plusOW_p80_tmp2_validation__gelderland__df_path,
)

In [80]:
idx__WD_plusOW_p80_tmp2_training__gelderland__df, idx__WD_plusOW_p80_tmp2_validation__gelderland__df, idx__WD_plusOW_p80_tmp2_test__gelderland__df, leftover_df, idx__WD_plusOW_p80_tmp2_summary__gelderland__df = training_validation_split_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD_plusOW__selected__gelderland__tmp2__df,
    year_cols=idx__WD_plusOW__selected__gelderland__tmp2__df.columns,
    cap_pixels_by_class=WD_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    seed=42,
    area_col="bedekkingsOppervlakte1",
    pixel_area_m2=100.0,
)

In [96]:
idx__WD_plusOW_p80_tmp2_summary__gelderland__df

,target_train_m2,got_train_m2,target_val_m2,got_val_m2,target_test_m2,got_test_m2,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Dry Nature,87500.0,88440.0,37500.0,39600.0,0.0,0.0,888,396,0,125054,0,0,51,26,0
Wet Nature,17500.0,15900.0,7500.0,5287.0,0.0,0.0,155,45,0,0,0,0,24,2,0
No-Habitat,87500.0,88700.0,37500.0,39300.0,0.0,0.0,887,393,0,171782,0,0,56,28,0
Semi-Wet Nature,35000.0,38400.0,15000.0,15100.0,0.0,0.0,386,151,0,1251,0,0,36,6,0
Open water,17500.0,19096.0,7500.0,7618.0,0.0,0.0,234,93,0,3840,0,0,11,7,0

In [81]:
idx__WD_plusOW_p80_tmp2_training__gelderland__df.to_pickle(idx__WD_plusOW_p80_tmp2_training__gelderland__df_path)
idx__WD_plusOW_p80_tmp2_validation__gelderland__df.to_pickle(idx__WD_plusOW_p80_tmp2_validation__gelderland__df_path)

In [82]:
idx__WD1_plusOW_p80_tmp2_training__gelderland__df, idx__WD1_plusOW_p80_tmp2_validation__gelderland__df, idx__WD1_plusOW_p80_tmp2_test__gelderland__df, leftover_df, idx__WD1_plusOW_p80_tmp2_summary__gelderland__df = training_validation_split_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD1_plusOW__selected__gelderland__tmp2__df,
    year_cols=idx__WD1_plusOW__selected__gelderland__tmp2__df.columns,
    cap_pixels_by_class=WD1_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    seed=42,
    area_col="bedekkingsOppervlakte1",
    pixel_area_m2=100.0,
)

In [97]:
idx__WD1_plusOW_p80_tmp2_summary__gelderland__df

,target_train_m2,got_train_m2,target_val_m2,got_val_m2,target_test_m2,got_test_m2,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,210000.0,211936.0,90000.0,90160.0,0.0,0.0,2127,903,0,292260,0,0,128,61,0
Wet Nature,98000.0,72032.0,42000.0,14051.0,0.0,0.0,710,141,0,0,0,0,71,9,0
Open water,21000.0,22697.0,9000.0,10153.0,0.0,0.0,250,147,0,2121,0,0,13,8,0

In [83]:
idx__WD1_plusOW_p80_tmp2_training__gelderland__df.to_pickle(idx__WD1_plusOW_p80_tmp2_training__gelderland__df_path)
idx__WD1_plusOW_p80_tmp2_validation__gelderland__df.to_pickle(idx__WD1_plusOW_p80_tmp2_validation__gelderland__df_path)

In [84]:
idx__WD2_plusOW_p80_tmp2_training__gelderland__df, idx__WD2_plusOW_p80_tmp2_validation__gelderland__df, idx__WD2_plusOW_p80_tmp2_test__gelderland__df, leftover_df, idx__WD2_plusOW_p80_tmp2_summary__gelderland__df = training_validation_split_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD2_plusOW__selected__gelderland__tmp2__df,
    year_cols=idx__WD2_plusOW__selected__gelderland__tmp2__df.columns,
    cap_pixels_by_class=WD2_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    seed=42,
    area_col="bedekkingsOppervlakte1",
    pixel_area_m2=100.0,
)

In [98]:
idx__WD2_plusOW_p80_tmp2_summary__gelderland__df

,target_train_m2,got_train_m2,target_val_m2,got_val_m2,target_test_m2,got_test_m2,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,87500.0,88996.0,37500.0,38900.0,0.0,0.0,894,389,0,298089,0,0,53,25,0
Semi-Wet Nature,35000.0,35096.0,15000.0,16600.0,0.0,0.0,353,166,0,180,0,0,38,6,0
Wet Nature,17500.0,16287.0,7500.0,4100.0,0.0,0.0,151,41,0,0,0,0,21,2,0
Open water,17500.0,17516.0,7500.0,9197.0,0.0,0.0,214,124,0,4665,0,0,13,6,0

In [85]:
idx__WD2_plusOW_p80_tmp2_training__gelderland__df.to_pickle(idx__WD2_plusOW_p80_tmp2_training__gelderland__df_path)
idx__WD2_plusOW_p80_tmp2_validation__gelderland__df.to_pickle(idx__WD2_plusOW_p80_tmp2_validation__gelderland__df_path)

In [86]:
idx__WD3_plusOW_p80_tmp2_training__gelderland__df, idx__WD3_plusOW_p80_tmp2_validation__gelderland__df, idx__WD3_plusOW_p80_tmp2_test__gelderland__df, leftover_df, idx__WD3_plusOW_p80_tmp2_summary__gelderland__df = training_validation_split_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD3_plusOW__selected__gelderland__tmp2__df,
    year_cols=idx__WD3_plusOW__selected__gelderland__tmp2__df.columns,
    cap_pixels_by_class=WD3_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    seed=42,
    area_col="bedekkingsOppervlakte1",
    pixel_area_m2=100.0,
)

In [99]:
idx__WD3_plusOW_p80_tmp2_summary__gelderland__df

,target_train_m2,got_train_m2,target_val_m2,got_val_m2,target_test_m2,got_test_m2,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,175000.0,178300.0,75000.0,75900.0,0.0,0.0,1789,759,0,115917,0,0,99,55,0
Wet Nature,91000.0,69583.0,39000.0,19500.0,0.0,0.0,686,195,0,0,0,0,71,9,0
Open water,21000.0,21972.0,9000.0,10493.0,0.0,0.0,277,131,0,3041,0,0,15,7,0

In [87]:
idx__WD3_plusOW_p80_tmp2_training__gelderland__df.to_pickle(idx__WD3_plusOW_p80_tmp2_training__gelderland__df_path)
idx__WD3_plusOW_p80_tmp2_validation__gelderland__df.to_pickle(idx__WD3_plusOW_p80_tmp2_validation__gelderland__df_path)

In [88]:
idx__WD4_plusOW_p80_tmp2_training__gelderland__df, idx__WD4_plusOW_p80_tmp2_validation__gelderland__df, idx__WD4_plusOW_p80_tmp2_test__gelderland__df, leftover_df, idx__WD4_plusOW_p80_tmp2_summary__gelderland__df = training_validation_split_func(
    gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
    idx_df=idx__WD4_plusOW__selected__gelderland__tmp2__df,
    year_cols=idx__WD4_plusOW__selected__gelderland__tmp2__df.columns,
    cap_pixels_by_class=WD4_dict,
    train_pct=0.7,
    val_pct=0.3,
    test_pct=0.0,
    seed=42,
    area_col="bedekkingsOppervlakte1",
    pixel_area_m2=100.0,
)

In [100]:
idx__WD4_plusOW_p80_tmp2_summary__gelderland__df

,target_train_m2,got_train_m2,target_val_m2,got_val_m2,target_test_m2,got_test_m2,n_train_ids,n_val_ids,n_test_ids,n_leftover_ids,n_unavailable_ids_ignored,n_invalid_ids_ignored,n_polygons_selected,n_large_polygons_selected,n_seed_isolated_discarded
class_name,,,,,,,,,,,,,,,
Remaining,87500.0,90040.0,37500.0,39960.0,0.0,0.0,904,402,0,119350,0,0,52,30,0
Semi-Wet Nature,35000.0,35396.0,15000.0,18000.0,0.0,0.0,356,180,0,163,0,0,37,6,0
Wet Nature,17500.0,15125.0,7500.0,5262.0,0.0,0.0,142,50,0,0,0,0,21,2,0
Open water,21000.0,21015.0,9000.0,9302.0,0.0,0.0,258,102,0,3593,0,0,13,7,0

In [89]:
idx__WD4_plusOW_p80_tmp2_training__gelderland__df.to_pickle(idx__WD4_plusOW_p80_tmp2_training__gelderland__df_path)
idx__WD4_plusOW_p80_tmp2_validation__gelderland__df.to_pickle(idx__WD4_plusOW_p80_tmp2_validation__gelderland__df_path)

#### saving the training/validation gpkgs

In [90]:
# Setting dir
from functions._00_file_paths import (
    # --- IDX training/validation dfs ---
    habitat_kart__WD_plusOW_p80_tmp2__training__gelderland__gpkg_path,
    habitat_kart__WD_plusOW_p80_tmp2__validation__gelderland__gpkg_path,
    habitat_kart__WD1_plusOW_p80_tmp2__training__gelderland__gpkg_path,
    habitat_kart__WD1_plusOW_p80_tmp2__validation__gelderland__gpkg_path,
    habitat_kart__WD2_plusOW_p80_tmp2__training__gelderland__gpkg_path,
    habitat_kart__WD2_plusOW_p80_tmp2__validation__gelderland__gpkg_path,
    habitat_kart__WD3_plusOW_p80_tmp2__training__gelderland__gpkg_path,
    habitat_kart__WD3_plusOW_p80_tmp2__validation__gelderland__gpkg_path,
    habitat_kart__WD4_plusOW_p80_tmp2__training__gelderland__gpkg_path,
    habitat_kart__WD4_plusOW_p80_tmp2__validation__gelderland__gpkg_path,
)

In [91]:
# WD Training
habitat_kart__WD_plusOW_p80_tmp2__training__gelderland__gdf = idx_to_training_validation_gdf_func(
    idx_df=idx__WD_plusOW_p80_tmp2_training__gelderland__df, 
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

habitat_kart__WD_plusOW_p80_tmp2__training__gelderland__gdf.to_file(
    filename=habitat_kart__WD_plusOW_p80_tmp2__training__gelderland__gpkg_path,
    driver="GPKG"
)

# WD Validation
habitat_kart__WD_plusOW_p80_tmp2__validation__gelderland__gdf = idx_to_training_validation_gdf_func(
    idx_df=idx__WD_plusOW_p80_tmp2_validation__gelderland__df, 
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

habitat_kart__WD_plusOW_p80_tmp2__validation__gelderland__gdf.to_file(
    filename=habitat_kart__WD_plusOW_p80_tmp2__validation__gelderland__gpkg_path,
    driver="GPKG"
)

In [92]:
# WD1 Training
habitat_kart__WD1_plusOW_p80_tmp2__training__gelderland__gdf = idx_to_training_validation_gdf_func(
    idx_df=idx__WD1_plusOW_p80_tmp2_training__gelderland__df, 
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

habitat_kart__WD1_plusOW_p80_tmp2__training__gelderland__gdf.to_file(
    filename=habitat_kart__WD1_plusOW_p80_tmp2__training__gelderland__gpkg_path,
    driver="GPKG"
)

# WD1 Validation
habitat_kart__WD1_plusOW_p80_tmp2__validation__gelderland__gdf = idx_to_training_validation_gdf_func(
    idx_df=idx__WD1_plusOW_p80_tmp2_validation__gelderland__df, 
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

habitat_kart__WD1_plusOW_p80_tmp2__validation__gelderland__gdf.to_file(
    filename=habitat_kart__WD1_plusOW_p80_tmp2__validation__gelderland__gpkg_path,
    driver="GPKG"
)

In [93]:
# WD2 Training
habitat_kart__WD2_plusOW_p80_tmp2__training__gelderland__gdf = idx_to_training_validation_gdf_func(
    idx_df=idx__WD2_plusOW_p80_tmp2_training__gelderland__df, 
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

habitat_kart__WD2_plusOW_p80_tmp2__training__gelderland__gdf.to_file(
    filename=habitat_kart__WD2_plusOW_p80_tmp2__training__gelderland__gpkg_path,
    driver="GPKG"
)

# WD2 Validation
habitat_kart__WD2_plusOW_p80_tmp2__validation__gelderland__gdf = idx_to_training_validation_gdf_func(
    idx_df=idx__WD2_plusOW_p80_tmp2_validation__gelderland__df, 
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

habitat_kart__WD2_plusOW_p80_tmp2__validation__gelderland__gdf.to_file(
    filename=habitat_kart__WD2_plusOW_p80_tmp2__validation__gelderland__gpkg_path,
    driver="GPKG"
)

In [94]:
# WD3 Training
habitat_kart__WD3_plusOW_p80_tmp2__training__gelderland__gdf = idx_to_training_validation_gdf_func(
    idx_df=idx__WD3_plusOW_p80_tmp2_training__gelderland__df, 
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

habitat_kart__WD3_plusOW_p80_tmp2__training__gelderland__gdf.to_file(
    filename=habitat_kart__WD3_plusOW_p80_tmp2__training__gelderland__gpkg_path,
    driver="GPKG"
)

# WD3 Validation
habitat_kart__WD3_plusOW_p80_tmp2__validation__gelderland__gdf = idx_to_training_validation_gdf_func(
    idx_df=idx__WD3_plusOW_p80_tmp2_validation__gelderland__df, 
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

habitat_kart__WD3_plusOW_p80_tmp2__validation__gelderland__gdf.to_file(
    filename=habitat_kart__WD3_plusOW_p80_tmp2__validation__gelderland__gpkg_path,
    driver="GPKG"
)

In [95]:
# WD Training
habitat_kart__WD4_plusOW_p80_tmp2__training__gelderland__gdf = idx_to_training_validation_gdf_func(
    idx_df=idx__WD4_plusOW_p80_tmp2_training__gelderland__df, 
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

habitat_kart__WD4_plusOW_p80_tmp2__training__gelderland__gdf.to_file(
    filename=habitat_kart__WD4_plusOW_p80_tmp2__training__gelderland__gpkg_path,
    driver="GPKG"
)

# WD Validation
habitat_kart__WD4_plusOW_p80_tmp2__validation__gelderland__gdf = idx_to_training_validation_gdf_func(
    idx_df=idx__WD4_plusOW_p80_tmp2_validation__gelderland__df, 
    source_gdf=habitat_kart_plusOW__FC_p80_tmp2_selected__gelderland__RD__gdf,
)

habitat_kart__WD4_plusOW_p80_tmp2__validation__gelderland__gdf.to_file(
    filename=habitat_kart__WD4_plusOW_p80_tmp2__validation__gelderland__gpkg_path,
    driver="GPKG"
)