In [13]:
from paths.OG_paths import (
    idx__WD1_plusOW_p80_tmp2_training_at1__gelderland__df_path,
    idx__WD1_plusOW_p80_tmp2_validation_at1__gelderland__df_path,
    training_polys__WD1_plusOW_p80_tmp2_at1__gelderland__RD__gpkg_path,
    validation_pixels__WD1_plusOW_p80_tmp2_at1__gelderland__RD__gpkg_path,
)

In [9]:
import pandas as pd
import geopandas as gpd

In [4]:
idx__WD1_plusOW_p80_tmp2_training_at1__gelderland__df = pd.read_pickle(idx__WD1_plusOW_p80_tmp2_training_at1__gelderland__df_path)

In [5]:
idx__WD1_plusOW_p80_tmp2_training_at1__gelderland__df

,2017,2018,2019,2020,2021,2022,2023,2024
Remaining,"[GI_14631_2, GI_14631_3, GI_14732_1, GI_14732_...","[GI_18627_1, GI_18627_2, GI_18627_3, GI_18888_...","[GI_10075_1, GI_10075_10, GI_10075_11, GI_1007...","[GI_10141_1, GI_10141_10, GI_10141_2, GI_10141...","[GI_11304_11, GI_11304_12, GI_11304_13, GI_113...","[GI_44881_1, GI_44881_10, GI_44881_11, GI_4488...","[GI_219_1, GI_219_10, GI_219_11, GI_219_2, GI_...",[]
Wet Nature,"[GI_41299_1, GI_41299_2, GI_41299_3, GI_41299_...","[GI_18984_11, GI_18984_12, GI_18984_13, GI_189...",[],"[GI_12951_1, GI_12951_2, GI_12951_3, GI_12951_...",[],"[GI_44936_1, GI_44936_10, GI_44936_11, GI_4493...",[],[]
Open water,[],[],[],[],"[OW_11_1, OW_11_10, OW_11_11, OW_11_12, OW_11_...","[OW_13_10, OW_13_11, OW_13_12, OW_13_13, OW_13...","[OW_21_1, OW_21_10, OW_21_11, OW_21_12, OW_21_...","[OW_10_1, OW_10_10, OW_10_11, OW_10_12, OW_10_..."

In [12]:
gpd.read_file(training_polys__WD1_plusOW_p80_tmp2_at1__gelderland__RD__gpkg_path)

,polygon_id,Type,years,geometry
0,GI_14631,Remaining,2017,"MULTIPOLYGON (((182439.305 464463.083, 182439...."
1,GI_14732,Remaining,2017,"MULTIPOLYGON (((182359.317 464673.053, 182359...."
2,GI_14750,Remaining,2017,"MULTIPOLYGON (((182139.348 464523.075, 182129...."
3,GI_14756,Remaining,2017,"MULTIPOLYGON (((183729.122 464743.043, 183719...."
4,GI_14843,Remaining,2017,"MULTIPOLYGON (((181929.378 464973.011, 181929...."
...,...,...,...,...
152,OW_21,Open water,2023,"MULTIPOLYGON (((185488.873 459093.845, 185488...."
153,OW_1,Open water,2024,"MULTIPOLYGON (((200276.781 497598.412, 200276...."
154,OW_10,Open water,2024,"MULTIPOLYGON (((177659.983 451274.968, 177659...."
155,OW_12,Open water,2024,"MULTIPOLYGON (((183969.088 448215.388, 183969...."
156,OW_9,Open water,2024,"MULTIPOLYGON (((181029.469 459313.848, 181029...."

In [6]:
idx__WD1_plusOW_p80_tmp2_validation_at1__gelderland__df = pd.read_pickle(idx__WD1_plusOW_p80_tmp2_validation_at1__gelderland__df_path)

In [7]:
idx__WD1_plusOW_p80_tmp2_validation_at1__gelderland__df

,2017,2018,2019,2020,2021,2022,2023,2024
Remaining,"[GI_14622_12, GI_14622_13, GI_14622_14, GI_146...","[GI_19553_1, GI_19553_10, GI_19553_101, GI_195...","[GI_26354_28, GI_26354_29, GI_26354_30, GI_263...","[GI_169_11, GI_169_12, GI_169_13, GI_169_14, G...","[GI_16864_30, GI_16864_31, GI_16864_39, GI_168...",[],"[GI_182_1, GI_182_10, GI_182_11, GI_182_12, GI...",[]
Wet Nature,"[GI_45319_1, GI_45319_2, GI_45319_3, GI_45319_...","[GI_18556_11, GI_18556_12, GI_18556_13, GI_185...",[],"[GI_41773_1, GI_45861_1, GI_45861_2, GI_45861_3]",[],[],[],[]
Open water,[],"[OW_6_1, OW_6_10, OW_6_11, OW_6_12, OW_6_13, O...","[OW_2_1, OW_2_10, OW_2_11, OW_2_12, OW_2_13, O...",[],"[OW_5_112, OW_5_113, OW_5_114, OW_5_115, OW_5_...",[],[],[]

In [15]:
gpd.read_file(validation_pixels__WD1_plusOW_p80_tmp2_at1__gelderland__RD__gpkg_path)

,index,years,type,idx_layer,geometry
0,GI_15018_1,2017,Remaining,2017,"MULTIPOLYGON (((183209.196 466052.858, 183199...."
1,GI_15018_10,2017,Remaining,2017,"MULTIPOLYGON (((183199.198 466032.86, 183189.1..."
2,GI_15018_11,2017,Remaining,2017,"MULTIPOLYGON (((183209.196 466032.86, 183199.1..."
3,GI_15018_12,2017,Remaining,2017,"MULTIPOLYGON (((183219.195 466032.86, 183209.1..."
4,GI_15018_13,2017,Remaining,2017,"MULTIPOLYGON (((183229.193 466032.86, 183219.1..."
...,...,...,...,...,...
1205,OW_19_48,"2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024...",Open water,2024,"MULTIPOLYGON (((194387.61 447075.945, 194387.6..."
1206,OW_19_49,"2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024...",Open water,2024,"MULTIPOLYGON (((194397.609 447075.769, 194397...."
1207,OW_19_50,"2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024...",Open water,2024,"MULTIPOLYGON (((194407.608 447075.594, 194407...."
1208,OW_19_51,"2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024...",Open water,2024,"MULTIPOLYGON (((194417.606 447075.55, 194417.6..."
1209,OW_19_52,"2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024...",Open water,2024,"MULTIPOLYGON (((194427.605 447075.55, 194427.6..."