_This notebook builds a df that explains the abbreviation structure used throughout the notebooks._

## Importing Functions

In [1]:
# No functions needed in this Notebook

## Setting directory

In [2]:
from paths.OG_paths import (
    #######################################
    #            00_common_dfs            #
    #######################################
    # |    n02_habitat_reference_dfs      |
    # +===================================+ 
    explanation__hab_group_codes__df_path,
    explanation__tmp_codes__df_path,
    explanation__names_concention__df_path
)

## Importing packages

In [3]:
import pandas as pd
import pickle

pd.set_option('display.max_colwidth', None)

## Buiding selection-codes explanation table

In [4]:
index = ["AO", "HB", "FC", "WD", "S1", "S2"]
columns = ["Abbreviation", "Explanation", "Only H.... codes", "Cover = 100%"]

explanation__hab_group_codes__df = pd.DataFrame(index=index, columns=columns)

In [5]:
explanation__hab_group_codes__df.loc["AO"] = [
    "All Objects", "Contains all objects from the input .gpkgs", "False", "False"
]

explanation__hab_group_codes__df.loc["HB"] = [
    "Habitat", "Selected all objects with an H.... code", "True", "False"
]

explanation__hab_group_codes__df.loc["FC"] = [
    "Full Cover", "All objects with an H.... code + 100% cover", "True", "True"
]

explanation__hab_group_codes__df.loc["WD"] = [
    "Wet-Dry selection", "All habitat types divided into abiotic water conditions. (Open water, Wet, Semi-wet, Dry)",
    "True", "True"
]

explanation__hab_group_codes__df.loc["S1"] = [
    "Selection 1", "Only trainingdata with Vennen, Vochtige Heide, & Heideveentje", "True", "True"
]

explanation__hab_group_codes__df.loc["S2"] = [
    "Selection 2", "Yet to be defined", "unknown", "unknown"
]

In [6]:
explanation__hab_group_codes__df.to_pickle(explanation__hab_group_codes__df_path)

In [7]:
explanation__hab_group_codes__df.head()

,Abbreviation,Explanation,Only H.... codes,Cover = 100%
AO,All Objects,Contains all objects from the input .gpkgs,False,False
HB,Habitat,Selected all objects with an H.... code,True,False
FC,Full Cover,All objects with an H.... code + 100% cover,True,True
WD,Wet-Dry selection,"All habitat types divided into abiotic water conditions. (Open water, Wet, Semi-wet, Dry)",True,True
S1,Selection 1,"Only trainingdata with Vennen, Vochtige Heide, & Heideveentje",True,True

## Building Temporal-selection code df

In [8]:
index = ['tmp0', 'tmp1', 'tmp2']
columns = ['Explanation']

explanation__tmp_codes__df = pd.DataFrame(index=index, columns=columns)

In [9]:
explanation__tmp_codes__df.loc['tmp0'] = [
    "All years separate: .... | 2000 | 2001 | ...."
]

explanation__tmp_codes__df.loc['tmp1'] = [
    "Clustering of years 2010-2016. Then each year separate | 2017 | 2018 | .... "
]

explanation__tmp_codes__df.loc['tmp2'] = [
    "Only observations for the years | 2017 | 2018 | ... | 2024 "
]

In [10]:
explanation__tmp_codes__df.to_pickle(explanation__tmp_codes__df_path)

In [11]:
explanation__tmp_codes__df.head()

                                                                       Explanation
tmp0                                 All years separate: .... | 2000 | 2001 | ....
tmp1  Clustering of years 2010-2016. Then each year separate | 2017 | 2018 | ....
tmp2                   Only observations for the years | 2017 | 2018 | ... | 2024

End of this notebook