_This is an unfinished Notebook. Standardization of the translation from vegetation data to habitat data was unsuccessfull._

## Importing Functions

In [ ]:
# No Functions needed in this Notebook

## Checking and setting Directory

In [1]:
from paths.OG_paths import (
    #######################################
    #       HABITAT / VEGETATION DATA     #
    #######################################
    # |    T0 Habitatkart Veluwe [RAW]    |
    # +===================================+ 
    habitat_kart_T1__raw__bosgr_2020__RD__gpkg_path,
    habitat_kart_T1__raw__bosgr_2021__RD__gpkg_path,
    habitat_kart_T1__raw__bosgr_2022__RD__gpkg_path,
    habitat_kart_T1__raw__bosgr_2023__RD__gpkg_path,
    habitat_kart_T1__raw__bosgr_2024__RD__gpkg_path,
    habitat_kart_T1__raw__glk_2020__RD__gpkg_path,
    habitat_kart_T1__raw__glk_2021__RD__gpkg_path,
    habitat_kart_T1__raw__nm_2020__RD__gpkg_path,
    habitat_kart_T1__raw__nm_2021__RD__gpkg_path,
    habitat_kart_T1__raw__nphv_2023__RD__gpkg_path,
    habitat_kart_T1__raw__nphv_2024__RD__gpkg_path,
    habitat_kart_T1__raw__ah_2022__RD__gpkg_path,
    habitat_kart_T1__raw__eg_2024__RD__gpkg_path,
    habitat_kart_T1__raw__isk_2024__RD__gpkg_path,
    habitat_kart_T1__raw__vegpla_2020__RD__gpkg_path,
    habitat_kart_T1__raw__vegpla_2021__RD__gpkg_path,
    habitat_kart_T1__raw__vegpla_2021_2__RD__gpkg_path,
    habitat_kart_T1__raw__vegpla_2022__RD__gpkg_path,
    habitat_kart_T1__raw__vegpla_2023__RD__gpkg_path,
    habitat_kart_T1__raw__vegpla_2023_2__RD__gpkg_path,
    habitat_kart_T1__raw__vegpla_2024__RD__gpkg_path,
)

## Importing packagages

In [5]:
import pandas as pd
import matplotlib.pyplot as plt

# pd.set_option('display.max_colwidth', None)

## Creating a T1 veg kart to Hab codes translation df

In [6]:
# --- Robust Names df ---
habitat_reference__HB__df = pd.read_pickle(habitat_reference__HB__df_path)

In [7]:
# Create a new VvN translation df
habitat_reference__vvn__df = habitat_reference__HB__df

In [8]:
habitat_reference__vvn__df.loc['Not_tracked_veg'] = {
    "habitatnaam_disp": "Nan",
    "habitat_color": "Nan",
    "WD_division": "Nan",
    "WD_color": "Nan",
}

In [9]:
hab_codes_coupling = {
    'H0000': [''],
    'H2310': [''],
    'H2320': [''],
    'H2330': [''],
    'H3130': [''],
    'H3150': [''],
    'H3160': [''],
    'H3260A': [''],
    'H3260B': [''],
    'H3270': [''],
    'H4010A': [''],
    'H4030': [''],
    'H5130': [''],
    'H6120': [''],
    'H6230': [''],
    'H6410': [''],
    'H6430A': [''],
    'H6430B': [''],
    'H6430C': [''],
    'H6510A': [''],
    'H6510B': [''],
    'H7110A': [''],
    'H7110B': [''],
    'H7120': [''],
    'H7140A': [''],
    'H7150': [''],
    'H7210': [''],
    'H7230': [''],
    'H9120': [''],
    'H9160A': [''],
    'H9190': [''],
    'H91D0': [''],
    'H91E0A': [''],
    'H91E0B': [''],
    'H91E0C': [''],
    'H91F0': [''],
    'LGN_OW': [''],
    'Not_tracked_veg': [''],
}

In [10]:
# habitat_reference__vvn__df['vvn'] = habitat_reference__vvn__df.index.map(vvn_codes)

In [11]:
habitat_reference__vvn__df.head()

,habitatnaam_disp,habitat_color,WD_division,WD_color
habitatType,,,,
H0000,Geen habitattype,#999999,No-Habitat,#aaaaaa
H2310,Stuifzandheiden met struikhei,#fff7b2,Dry Nature,#ffff99
H2320,Binnenlandse kraaheibegroeiingen,#8c564b,Dry Nature,#ffff99
H2330,Zandverstuivingen,#e8d6c3,Dry Nature,#ffff99
H3130,Zwakgebufferde vennen,#9ed6f8,Wet Nature,#0c82d1

## Processing BOSGROEP files

In [12]:
check_gpkg_layers_func(habitat_kart_T1__raw__bosgr_2021__RD__gpkg_path)

['habitat_kart_T1__raw__bosgr_2021__RD__layer']

In [13]:
# bosgr 2020
habitat_kart_T1__raw__bosgr_2020__RD__gpkg = import_gpkg_func(
    gdf_path=habitat_kart_T1__raw__bosgr_2020__RD__gpkg_path,
    layer='habitat_kart_T1__raw__bosgr_2020__RD__layer',
    index_col='OBJECTID',
)

# bosgr 2021
habitat_kart_T1__raw__bosgr_2021__RD__gpkg = import_gpkg_func(
    gdf_path=habitat_kart_T1__raw__bosgr_2021__RD__gpkg_path,
    layer='habitat_kart_T1__raw__bosgr_2021__RD__layer',
    index_col='OBJECTID',
)

# bosgr 2022
habitat_kart_T1__raw__bosgr_2022__RD__gpkg = import_gpkg_func(
    gdf_path=habitat_kart_T1__raw__bosgr_2022__RD__gpkg_path,
    layer='habitat_kart_T1__raw__bosgr_2022__RD__layer',
    index_col='OBJECTID',
)

# bosgr 2023
habitat_kart_T1__raw__bosgr_2023__RD__gpkg = import_gpkg_func(
    gdf_path=habitat_kart_T1__raw__bosgr_2023__RD__gpkg_path,
    layer='habitat_kart_T1__raw__bosgr_2023__RD__layer',
    index_col='OBJECTID',
)

# bosgr 2024
habitat_kart_T1__raw__bosgr_2024__RD__gpkg = import_gpkg_func(
    gdf_path=habitat_kart_T1__raw__bosgr_2024__RD__gpkg_path,
    layer='habitat_kart_T1__raw__bosgr_2024__RD__layer',
    index_col='OBJECTID',
)

In [14]:
habitat_kart_T1__raw__bosgr_2020__RD__gpkg.columns

Index(['Shape_Length', 'Shape_Area', 'Lidnr', 'Objectnaam', 'LokType1',
       'LokTypB1', 'LandTyp1', 'Aandeel1', 'LokType2', 'LokTypB2', 'LandTyp2',
       'Aandeel2', 'LokType3', 'LokTypB3', 'LandTyp3', 'Aandeel3', 'Opmerking',
       'HabitType', 'HabitKwal', 'Waarnemer', 'Jaar', 'Label', 'Provincie',
       'RapportGebNr', 'RapportageGebied', 'geometry'],
      dtype='object')

In [25]:
habitat_kart_T1__raw__bosgr_2020__RD__gpkg.loc[15:20]

,Shape_Length,Shape_Area,Lidnr,Objectnaam,LokType1,LokTypB1,LandTyp1,Aandeel1,LokType2,LokTypB2,...,Opmerking,HabitType,HabitKwal,Waarnemer,Jaar,Label,Provincie,RapportGebNr,RapportageGebied,geometry
index,,,,,,,,,,,,,,,,,,,,,
15,172.177946,901.654272,10308,Vossebosch,HD1.1,"Droge heide met Struikhei, soortenarme variant",r20Aa01b,100,None,None,...,None,None,None,Unie van Bosgroepen_Maarten Immerzeel,2020,r20Aa01b,Gelderland,97,Het Zand,"MULTIPOLYGON Z (((223467.766 451036.561 0, 223..."
16,110.209206,816.005002,10308,Vossebosch,HD1.1,"Droge heide met Struikhei, soortenarme variant",r20Aa01b,100,None,None,...,None,None,None,Unie van Bosgroepen_Maarten Immerzeel,2020,r20Aa01b,Gelderland,97,Het Zand,"MULTIPOLYGON Z (((223441.661 450933.298 0, 223..."
17,340.205662,2143.256861,10708,Hoenderkamp,O1,Oevervegetatie met Watermunt en Grote wederik,r09Aa03,100,None,None,...,None,None,None,Unie van Bosgroepen_Maarten Immerzeel,2020,r09Aa03,Gelderland,97,Het Zand,"MULTIPOLYGON Z (((223208.987 450902.232 0, 223..."
18,66.664259,345.672387,10708,Hoenderkamp,O3,Oevervegetatie met moeraskruiden,r09Aa,100,None,None,...,None,None,None,Unie van Bosgroepen_Maarten Immerzeel,2020,r09Aa,Gelderland,97,Het Zand,"MULTIPOLYGON Z (((222569.222 450547.078 0, 222..."
19,457.063822,7200.831008,10265,Roekelse Bos,HD1.1,"Droge heide met Struikhei, soortenarme variant",r20Aa01b,100,None,None,...,None,None,None,Unie van Bosgroepen_Maarten Immerzeel,2020,r20Aa01b,Gelderland,38,Driesprong,"MULTIPOLYGON Z (((180968.645 455856.642 0, 180..."
20,433.951817,5275.425203,10265,Roekelse Bos,HD1.1,"Droge heide met Struikhei, soortenarme variant",r20Aa01b,100,None,None,...,None,None,None,Unie van Bosgroepen_Maarten Immerzeel,2020,r20Aa01b,Gelderland,38,Driesprong,"MULTIPOLYGON Z (((180965.245 455749.388 0, 180..."

In [26]:
habitat_kart_T1__raw__bosgr_2020__RD__gpkg[habitat_kart_T1__raw__bosgr_2020__RD__gpkg["LandTyp1"]=='r16RG28']

,Shape_Length,Shape_Area,Lidnr,Objectnaam,LokType1,LokTypB1,LandTyp1,Aandeel1,LokType2,LokTypB2,...,Opmerking,HabitType,HabitKwal,Waarnemer,Jaar,Label,Provincie,RapportGebNr,RapportageGebied,geometry
index,,,,,,,,,,,,,,,,,,,,,
50,122.366945,635.558505,10017,Klootsemastraat,M3,Natte laagte met veldrus en grote kattenstaart,r16RG28,100,None,None,...,None,None,None,Unie van Bosgroepen_Penelope van Wijhe,2020,r16RG28,Gelderland,95,Bronckhorst,"MULTIPOLYGON Z (((217107.026 444831.351 0, 217..."
51,198.206272,1527.490977,10017,Klootsemastraat,M3,Natte laagte met veldrus en grote kattenstaart,r16RG28,100,None,None,...,None,None,None,Unie van Bosgroepen_Penelope van Wijhe,2020,r16RG28,Gelderland,95,Bronckhorst,"MULTIPOLYGON Z (((217282.541 445054.429 0, 217..."
52,194.858486,1850.918981,10017,Klootsemastraat,M3,Natte laagte met veldrus en grote kattenstaart,r16RG28,100,None,None,...,None,None,None,Unie van Bosgroepen_Penelope van Wijhe,2020,r16RG28,Gelderland,95,Bronckhorst,"MULTIPOLYGON Z (((217222.561 445030.287 0, 217..."
54,151.643832,1249.871205,10017,Klootsemastraat,M3,Natte laagte met veldrus en grote kattenstaart,r16RG28,100,None,None,...,None,None,None,Unie van Bosgroepen_Penelope van Wijhe,2020,r16RG28,Gelderland,95,Bronckhorst,"MULTIPOLYGON Z (((217157.025 444921.613 0, 217..."
56,283.152888,2179.562051,10017,Klootsemastraat,M3,Natte laagte met veldrus en grote kattenstaart,r16RG28,100,None,None,...,None,None,None,Unie van Bosgroepen_Penelope van Wijhe,2020,r16RG28,Gelderland,95,Bronckhorst,"MULTIPOLYGON Z (((217038.664 444951.963 0, 217..."

In [17]:
# selecting only relevant columns from Bosgr gdf
cols_to_keep_bosgr = ['Shape_Area', 'LokType1', 'LokTypB1', 'LandTyp1', 'Aandeel1', 'HabitType', 'Jaar', 'Label', 'geometry']

In [18]:
habitat_kart_T1__step1__bosgr_2020__RD__gpkg = habitat_kart_T1__raw__bosgr_2020__RD__gpkg[cols_to_keep_bosgr]
habitat_kart_T1__step1__bosgr_2021__RD__gpkg = habitat_kart_T1__raw__bosgr_2021__RD__gpkg[cols_to_keep_bosgr]
habitat_kart_T1__step1__bosgr_2022__RD__gpkg = habitat_kart_T1__raw__bosgr_2022__RD__gpkg[cols_to_keep_bosgr]
habitat_kart_T1__step1__bosgr_2023__RD__gpkg = habitat_kart_T1__raw__bosgr_2023__RD__gpkg[cols_to_keep_bosgr]
habitat_kart_T1__step1__bosgr_2024__RD__gpkg = habitat_kart_T1__raw__bosgr_2024__RD__gpkg[cols_to_keep_bosgr]

In [19]:
habitat_kart_T1__step1__bosgr_2020__RD__gpkg['LandTyp1'].unique()

array(['r20Aa01c', 'r20Aa01b', 'r14RG05', 'r19RG02', 'r20RG01', 'r10',
       None, 'r09Aa03', 'r09Aa', 'r10DG01', 'r09RG01', 'r06RG05',
       'r08Bb04c', 'r41Aa', 'r45Aa03', 'r20Aa01', 'r16RG28', 'r09RG10',
       'r14B', 'r44Aa'], dtype=object)

In [20]:
habitat_kart_T1__step1__bosgr_2021__RD__gpkg['LandTyp1'].unique()

array(['r20Aa01b', 'r20Aa02', 'r10RG06', 'r20RG01', 'r12', 'r10DG01',
       'r10RG09', 'r44Aa03b', 'r10RG02', 'r10Aa02a', 'r11Aa02c',
       'r10RG05', 'r09RG01', None, 'r16RG21', 'r16RG11', 'r08Bb04c',
       'r33Aa01b', 'r08Bb04a'], dtype=object)

## GLK files

In [21]:
check_gpkg_layers_func(habitat_kart_T1__raw__glk_2020__RD__gpkg_path)

['habitat_kart_T1__raw__glk_2020__RD__layer']

In [22]:
# bosgr 2020
habitat_kart_T1__raw__glk_2020__RD__gdf = import_gpkg_func(
    gdf_path=habitat_kart_T1__raw__glk_2020__RD__gpkg_path,
    layer='habitat_kart_T1__raw__glk_2020__RD__layer',
    index_col='ID',
)

# bosgr 2021
habitat_kart_T1__raw__glk_2021__RD__gdf = import_gpkg_func(
    gdf_path=habitat_kart_T1__raw__glk_2021__RD__gpkg_path,
    layer='habitat_kart_T1__raw__glk_2021__RD__layer',
    index_col='fid_2',
)

In [23]:
habitat_kart_T1__raw__glk_2021__RD__gdf.columns

Index(['Loktype1', 'CodeType1', 'AbunType1', 'RvvN1Type1', 'RvvN2Type1',
       'Loktype2', 'CodeType2', 'AbunType2', 'RvvN1Type2', 'RvvN2Type2',
       'Loktype3', 'CodeType3', 'AbunType3', 'RvvN1Type3', 'RvvN2Type3',
       'Beukenlaan', 'Bochtige s', 'Dikke bome', 'Grijs Kron', 'Grote bran',
       'Pijpenstro', 'Pitrus', 'Solitaire', 'Vegetatiek', 'waarnemer',
       'opmerking', 'datum', 'Gebied', 'geometry'],
      dtype='object')

In [24]:
habitat_kart_T1__raw__glk_2021__RD__gdf.head()

,Loktype1,CodeType1,AbunType1,RvvN1Type1,RvvN2Type1,Loktype2,CodeType2,AbunType2,RvvN1Type2,RvvN2Type2,...,Grote bran,Pijpenstro,Pitrus,Solitaire,Vegetatiek,waarnemer,opmerking,datum,Gebied,geometry
index,,,,,,,,,,,,,,,,,,,,,
398,11-2 Pijpenstrootje dominant - typisch,11-2,100,r20RG01,None,None,None,NaN,None,None,...,None,51% en meer,None,None,Klasse der droge heiden,Wouter Koenders,None,2021/10/04 16:05:00.000,Loenermark,"MULTIPOLYGON (((195379.044 454675.167, 195384...."
397,20A1-1 Struikhei en Dophei - Heidebremmen,20A1-1,100,r20Aa01b,None,None,None,NaN,None,None,...,None,6-25%,None,None,Klasse der droge heiden,Wouter Koenders,None,2021/10/04 15:25:35.000,Loenermark,"MULTIPOLYGON (((195395.052 454672.541, 195395...."
396,41A3-3 Dennenbos - Bosbessen,41A3-3,100,r44Aa03c,None,None,None,NaN,None,None,...,None,None,None,None,Klasse van de naaldbossen,Wouter Koenders,None,2021/10/04 15:07:08.000,Loenermark,"MULTIPOLYGON (((195393.957 454607.161, 195385...."
270,20-1 Struikhei en Dophei - Bochtige smele,20-1,90,r19RG02,None,14A1-3 Heidespurrie en Buntgras - stuifzandkor...,14A1-3,10.0,r14Aa01b,None,...,None,None,None,None,Klasse der heischrale graslanden,Wouter Koenders,None,2021/09/16 14:18:06.000,Loenermark,"MULTIPOLYGON (((195872.733 455210.52, 195872.2..."
404,20-1 Struikhei en Dophei - Bochtige smele,20-1,100,r19RG02,None,None,None,NaN,None,None,...,None,6-25%,None,None,Klasse der heischrale graslanden,Wouter Koenders,None,2021/10/08 10:02:46.000,Loenermark,"MULTIPOLYGON (((195762.547 455052.712, 195742...."

## NM files