_This Notebook builds dfs that keep track of the index (of each habitat polygon) based on each division. Note that the idx division build in this Notebook does NOT include the plusOW pixels. This was a first attempt, the dfs that track the pixels, go to "n01 build selected pixels idx dfs"_

## Importing Functions

In [1]:
from functions.gpkg_funcs import (
    check_gpkg_layers_func,
    import_gpkg_func,
)

from functions.custom_common_nb_funcs import (
    check_processing,
)

from functions.idx_builder_funcs import (
    tmp_0_idx_df_func,
    tmp_1_idx_df_func,
    tmp2_idx_df_func,
    HT_idx_df_func,
    FC_idx_df_func,
    group_idx_df_func,
)

## Setting directory

In [2]:
from paths.OG_paths import (
    #######################################
    #     01_pre_processing_hab_kart      #
    #######################################
    # |  n01_T0_habitat_gpkg_processing   |
    # +===================================+ 
    # --- Habitat kart Processed GPKG --- #
    habitat_kart__processed__gelderland__RD__gpkg_path,
    habitat_kart__processed__gelderland_minHR__RD__gpkg_path,
    habitat_kart__processed__website__RD__gpkg_path,
    habitat_kart__processed__website_plusHR__RD__gpkg_path,


    #######################################
    #            00_common_dfs            #
    #######################################
    # |    n01_habitat_reference_dfs      |
    # +===================================+ 
    habitat_reference__WD__df_path,
    habitat_reference__s__df_path,

    # +===================================+
    # |       n02_explanation_dfs         |
    # +===================================+ 
    explanation__hab_group_codes__df_path,
    explanation__tmp_codes__df_path,

    
    #######################################
    #  02_hab_kart_selection_and_division #
    #######################################
    # |      n01_first_data_division      |
    # +===================================+ 
    # AO tmp0
    idx__AO__division__gelderland__tmp0__df_path,
    idx__AO__division__gelderland_minHR__tmp0__df_path,
    idx__AO__division__website__tmp0__df_path,
    idx__AO__division__website_plusHR__tmp0__df_path,
    # AO tmp1
    idx__AO__division__gelderland__tmp1__df_path,
    idx__AO__division__gelderland_minHR__tmp1__df_path,
    idx__AO__division__website__tmp1__df_path,
    idx__AO__division__website_plusHR__tmp1__df_path,
    # HB tmp1
    idx__HB__division__gelderland__tmp1__df_path,
    idx__HB__division__gelderland_minHR__tmp1__df_path,
    idx__HB__division__website__tmp1__df_path,
    idx__HB__division__website_plusHR__tmp1__df_path,
    # FC tmp1
    idx__FC__division__gelderland__tmp1__df_path,
    idx__FC__division__gelderland_minHR__tmp1__df_path,
    idx__FC__division__website__tmp1__df_path,
    idx__FC__division__website_plusHR__tmp1__df_path,
    # WD tmp1
    idx__WD__division__gelderland__tmp1__df_path,
    idx__WD__division__gelderland_minHR__tmp1__df_path,
    idx__WD__division__website__tmp1__df_path,
    idx__WD__division__website_plusHR__tmp1__df_path,
    # s1 tmp1
    idx__s1__division__gelderland__tmp1__df_path,
    idx__s1__division__gelderland_minHR__tmp1__df_path,
    idx__s1__division__website__tmp1__df_path,
    idx__s1__division__website_plusHR__tmp1__df_path,
    # AO tmp2
    idx__AO__division__gelderland__tmp2__df_path,
    idx__AO__division__website_plusHR__tmp2__df_path,
    # HB tmp2
    idx__HB__division__gelderland__tmp2__df_path,
    idx__HB__division__website_plusHR__tmp2__df_path,
    # FC_p80 tmp2
    idx__FC_p80__division__gelderland__tmp2__df_path,
    idx__FC_p80__division__website_plusHR__tmp2__df_path,
)

## Importing packages

In [3]:
import pandas as pd

# pd.set_option('display.max_colwidth', None)

## Import Files

In [4]:
check_gpkg_layers_func(habitat_kart__processed__website_plusHR__RD__gpkg_path)

['habitat_kart__processed__website_plusHR__RD__layer']

In [5]:
# --- Habitat kart Processed GPKGs ---
# Gelderland 
habitat_kart__processed__gelderland__RD__gdf = import_gpkg_func(
    gdf_path=habitat_kart__processed__gelderland__RD__gpkg_path, 
    layer='habitat_kart__processed__gelderland__RD__layer', 
    index_col='index'
)

# Gelderland min hr 
habitat_kart__processed__gelderland_minHR__RD__gdf = import_gpkg_func(
    gdf_path=habitat_kart__processed__gelderland_minHR__RD__gpkg_path, 
    layer='habitat_kart__processed__gelderland_minHR__RD__layer', 
    index_col='index'
)

# Website 
habitat_kart__processed__website__RD__gdf = import_gpkg_func(
    gdf_path=habitat_kart__processed__website__RD__gpkg_path,
    layer='habitat_kart__processed__website__RD__layer',
    index_col='index'
)

# Website plus hr 
habitat_kart__processed__website_plusHR__RD__gdf = import_gpkg_func(
    gdf_path=habitat_kart__processed__website_plusHR__RD__gpkg_path,
    layer='habitat_kart__processed__website_plusHR__RD__layer',
    index_col='index'
)

c:\Users\NL1G3K\Desktop\Vegetation_quality_monitoring\.pixi\envs\default\Lib\site-packages\pyogrio\geopandas.py:49: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  res = pd.to_datetime(ser, **datetime_kwargs)
c:\Users\NL1G3K\Desktop\Vegetation_quality_monitoring\.pixi\envs\default\Lib\site-packages\pyogrio\geopandas.py:49: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  res = pd.to_datetime(ser, **datetime_kwargs)
c:\Users\NL1G3K\Desktop\Vegetation_quality_monitoring\.pixi\envs\default\Lib\site-packages\pyogrio\geopandas.py:49: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  res = pd.to_datetime(ser, **datetime_kwargs)
c:\Users\NL1G3K\Desktop\Vegetation_quality_monitoring\.pixi\envs\default\Lib\site-packages\pyogrio\geopandas.py:49: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  res = pd.to_datetime(ser, **datetime_kwargs)

In [6]:
# --- Selection reference dfs ---
habitat_reference__WD__df = pd.read_pickle(habitat_reference__WD__df_path)
habitat_reference__s__df = pd.read_pickle(habitat_reference__s__df_path)

# --- Explanation dfs ---
explanation__hab_group_codes__df = pd.read_pickle(explanation__hab_group_codes__df_path)
explanation__tmp_codes__df = pd.read_pickle(explanation__tmp_codes__df_path)

In [7]:
# Checking the import
values = [habitat_kart__processed__gelderland__RD__gdf.shape[0], habitat_kart__processed__gelderland_minHR__RD__gdf.shape[0],
          habitat_kart__processed__website__RD__gdf.shape[0], habitat_kart__processed__website_plusHR__RD__gdf.shape[0]]
entities = ["gelderland", "gelderland_min_hr", "website", "website_plus_hr"]

check_processing(values, entities, typ="AO", tmp="tmp0")

['The number of habitat surveys is correct']

## Information <br>

Explanation on the the coding used in this notebook for filtering

In [8]:
habitat_reference__WD__df.head()

,habitatnaam_disp,habitat_color,WD_division,WD_color,WD1_division,WD1_color,WD2_division,WD2_color,WD3_division,WD3_color,WD4_division,WD4_color,WD5_division,WD5_color
habitatType,,,,,,,,,,,,,,
H0000,Geen habitattype,#999999,No-Habitat,#aaaaaa,Remaining,#f54949,Remaining,#f54949,NaN,NaN,NaN,NaN,NaN,NaN
H2310,Stuifzandheiden met struikhei,#fff7b2,Dry Nature,#ffff99,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949
H2320,Binnenlandse kraaheibegroeiingen,#8c564b,Dry Nature,#ffff99,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949
H2330,Zandverstuivingen,#e8d6c3,Dry Nature,#ffff99,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949,Remaining,#f54949
H3130,Zwakgebufferde vennen,#9ed6f8,Wet Nature,#0c82d1,Wet Nature,#0c82d1,Wet Nature,#0c82d1,Wet Nature,#0c82d1,Wet Nature,#0c82d1,Open water,#003f69

In [9]:
habitat_reference__s__df.head()

,habitatnaam_disp,habitat_color,s1_division,s2_division
habitatType,,,,
H0000,Geen habitattype,#999999,NaN,NaN
H2310,Stuifzandheiden met struikhei,#fff7b2,Remaining,Remaining
H2320,Binnenlandse kraaheibegroeiingen,#8c564b,Remaining,Remaining
H2330,Zandverstuivingen,#e8d6c3,Remaining,Remaining
H3130,Zwakgebufferde vennen,#9ed6f8,Zwakgebufferde vennen,Ven

In [10]:
explanation__hab_group_codes__df

,Abbreviation,Explanation,Only H.... codes,Cover = 100%
AO,All Objects,Contains all objects from the input .gpkgs,False,False
HB,Habitat,Selected all objects with an H.... code,True,False
FC,Full Cover,All objects with an H.... code + 100% cover,True,True
WD,Wet-Dry selection,All habitat types divided into abiotic water c...,True,True
S1,Selection 1,"Only trainingdata with Vennen, Vochtige Heide,...",True,True
S2,Selection 2,Yet to be defined,unknown,unknown

In [11]:
explanation__tmp_codes__df

                                            Explanation
tmp0      All years separate: .... | 2000 | 2001 | ....
tmp1  Clustering of years 2010-2016. Then each year ...
tmp2  Only observations for the years | 2017 | 2018 ...

## Making IDX tables for AO [tmp0 & tmp1 & tmp2]

### IDX AO tmp0

In [12]:
# AO tmp0 IDX table
idx__AO__division__gelderland__tmp0__df, idx__AO__division__gelderland__tmp0__count = tmp_0_idx_df_func(habitat_kart__processed__gelderland__RD__gdf)
idx__AO__division__gelderland_minHR__tmp0__df, idx__AO__division__gelderland_minHR__tmp0__count = tmp_0_idx_df_func(habitat_kart__processed__gelderland_minHR__RD__gdf)
idx__AO__division__website__tmp0__df, idx__AO__division__website__tmp0__count = tmp_0_idx_df_func(habitat_kart__processed__website__RD__gdf)
idx__AO__division__website_plusHR__tmp0__df, idx__AO__division__website_plusHR__tmp0__count = tmp_0_idx_df_func(habitat_kart__processed__website_plusHR__RD__gdf)

In [13]:
# Check AO tmp0 processing
values = [idx__AO__division__gelderland__tmp0__count, idx__AO__division__gelderland_minHR__tmp0__count,
          idx__AO__division__website__tmp0__count, idx__AO__division__website_plusHR__tmp0__count]
entities = ["gelderland", "gelderland_min_hr", "website", "website_plus_hr"]

check_processing(values, entities, typ="AO", tmp="tmp0")

['The number of habitat surveys is correct']

In [14]:
# Save
idx__AO__division__gelderland__tmp0__df.to_pickle(idx__AO__division__gelderland__tmp0__df_path)
idx__AO__division__gelderland_minHR__tmp0__df.to_pickle(idx__AO__division__gelderland_minHR__tmp0__df_path)
idx__AO__division__website__tmp0__df.to_pickle(idx__AO__division__website__tmp0__df_path)
idx__AO__division__website_plusHR__tmp0__df.to_pickle(idx__AO__division__website_plusHR__tmp0__df_path)

### IDX AO tmp1

In [15]:
# AO tmp1 IDX table
idx__AO__division__gelderland__tmp1__df, idx__AO__division__gelderland__tmp1__count = tmp_1_idx_df_func(
    gdf=habitat_kart__processed__gelderland__RD__gdf,
    group_col='habitatnaam_1_disp',
    year_col='years'
)
idx__AO__division__gelderland_minHR__tmp1__df, idx__AO__division__gelderland_minHR__tmp1__count = tmp_1_idx_df_func(
    gdf=habitat_kart__processed__gelderland_minHR__RD__gdf,
    group_col='habitatnaam_1_disp',
    year_col='years'
)
idx__AO__division__website__tmp1__df, idx__AO__division__website__tmp1__count = tmp_1_idx_df_func(
    gdf=habitat_kart__processed__website__RD__gdf,
    group_col='habitatnaam_1_disp',
    year_col='years'
)
idx__AO__division__website_plusHR__tmp1__df, idx__AO__division__website_plusHR__tmp1__count = tmp_1_idx_df_func(
    gdf=habitat_kart__processed__website_plusHR__RD__gdf,
    group_col='habitatnaam_1_disp',
    year_col='years'
)

In [16]:
# Check AO tmp1 processing
values = [idx__AO__division__gelderland__tmp1__count, idx__AO__division__gelderland_minHR__tmp1__count,
          idx__AO__division__website__tmp1__count, idx__AO__division__website_plusHR__tmp1__count]
entities = ["gelderland", "gelderland_min_hr", "website", "website_plus_hr"]

check_processing(values, entities, typ="AO", tmp="tmp1")

['The number of habitat surveys is correct']

In [17]:
# Save
idx__AO__division__gelderland__tmp1__df.to_pickle(idx__AO__division__gelderland__tmp1__df_path)
idx__AO__division__gelderland_minHR__tmp1__df.to_pickle(idx__AO__division__gelderland_minHR__tmp1__df_path)
idx__AO__division__website__tmp1__df.to_pickle(idx__AO__division__website__tmp1__df_path)
idx__AO__division__website_plusHR__tmp1__df.to_pickle(idx__AO__division__website_plusHR__tmp1__df_path)

### IDX AO tmp2

In [18]:
# AO tmp2 idx df (tmp2 = 2017-> 2024 ONLY)
idx__AO__division__gelderland__tmp2__df, idx__AO__division__gelderland__tmp2__count = tmp2_idx_df_func(
    gdf=habitat_kart__processed__gelderland__RD__gdf,
    group_col='habitatnaam_1_disp',
    year_col='years',
)
idx__AO__division__website_plusHR__tmp2__df, idx__AO__division__website_plusHR__tmp2__count = tmp2_idx_df_func(
    gdf=habitat_kart__processed__website_plusHR__RD__gdf,
    group_col='habitatnaam_1_disp',
    year_col='years',
)

In [19]:
# Save
idx__AO__division__gelderland__tmp2__df.to_pickle(idx__AO__division__gelderland__tmp2__df_path)
idx__AO__division__website_plusHR__tmp2__df.to_pickle(idx__AO__division__website_plusHR__tmp2__df_path)

## Making IDX tables for HB

### IDX HB tmp1

In [20]:
# HB tmp1 idx df
idx__HB__division__gelderland__tmp1__df, idx__HB__division__gelderland__tmp1__count = HT_idx_df_func(
    gdf=habitat_kart__processed__gelderland__RD__gdf,
    idx_df=idx__AO__division__gelderland__tmp1__df,
    habitat_types_df=habitat_reference__WD__df,
    habitat_col='habitatType1'
)

idx__HB__division__gelderland_minHR__tmp1__df, idx__HB__division__gelderland_minHR__tmp1__count = HT_idx_df_func(
    gdf=habitat_kart__processed__gelderland_minHR__RD__gdf,
    idx_df=idx__AO__division__gelderland_minHR__tmp1__df,
    habitat_types_df=habitat_reference__WD__df,
    habitat_col='habitatType1'
)

idx__HB__division__website__tmp1__df, idx__HB__division__website__tmp1_count = HT_idx_df_func(
    gdf=habitat_kart__processed__website__RD__gdf,
    idx_df=idx__AO__division__website__tmp1__df,
    habitat_types_df=habitat_reference__WD__df,
    habitat_col='habitatType1'
)

idx__HB__division__website_plusHR__tmp1__df, idx__HB__division__website_plusHR__tmp1__count = HT_idx_df_func(
    gdf=habitat_kart__processed__website_plusHR__RD__gdf,
    idx_df=idx__AO__division__website_plusHR__tmp1__df,
    habitat_types_df=habitat_reference__WD__df,
    habitat_col='habitatType1'
)

In [21]:
# Check HB tmp1 processing
values = [idx__HB__division__gelderland__tmp1__count, idx__HB__division__gelderland_minHR__tmp1__count,
          idx__HB__division__website__tmp1_count, idx__HB__division__website_plusHR__tmp1__count]
entities = ["gelderland", "gelderland_min_hr", "website", "website_plus_hr"]

check_processing(values, entities, typ="HB", tmp="tmp1")

['The number of habitat surveys is correct']

In [22]:
idx__HB__division__gelderland__tmp1__df.head()

_year_str,2010-2016,2017,2018,2019,2020,2021,2022,2023,2024
index,,,,,,,,,
Actieve hoogvenen (heideveentjes),"[GI_44980, GI_4504, GI_4517, GI_4520, GI_4522,...",[],"[GI_24249, GI_24294, GI_24977, GI_39706]",[],[],[],[],[],[]
Beken & rivieren met waterplanten,"[GI_11591, GI_11113, GI_45974, GI_45985, GI_45...","[GI_45639, GI_45710]","[GI_149, GI_150, GI_202, GI_203, GI_204, GI_10...",[],"[GI_35887, GI_39913, GI_39985]",[],[],[],[]
Beuken-eikenbossen,"[GI_2798, GI_2812, GI_3711, GI_3728, GI_5048, ...","[GI_41687, GI_45356]","[GI_34126, GI_34166, GI_43607, GI_47606]","[GI_4967, GI_10067, GI_14182, GI_25289, GI_258...","[GI_4984, GI_10195, GI_10224, GI_10229, GI_102...","[GI_36114, GI_36116, GI_36120, GI_36127, GI_36...",[],[],[]
Binnenlandse kraaheibegroeiingen,"[GI_25398, GI_25509, GI_25677, GI_25679, GI_25...",[],"[GI_21499, GI_21504, GI_43502, GI_43639, GI_43...","[GI_44047, GI_44078, GI_44086, GI_44111, GI_44...","[GI_43654, GI_45825]",[],[],[],[]
Blauwgraslanden,[],[GI_41965],"[GI_24219, GI_24226, GI_24259, GI_24286, GI_24...",[],"[GI_18778, GI_18789, GI_18793]",[],[],[],[]

In [23]:
# Save
idx__HB__division__gelderland__tmp1__df.to_pickle(idx__HB__division__gelderland__tmp1__df_path)
idx__HB__division__gelderland_minHR__tmp1__df.to_pickle(idx__HB__division__gelderland_minHR__tmp1__df_path)
idx__HB__division__website__tmp1__df.to_pickle(idx__HB__division__website__tmp1__df_path)
idx__HB__division__website_plusHR__tmp1__df.to_pickle(idx__HB__division__website_plusHR__tmp1__df_path)

### IDX HB tmp2

In [24]:
# HB tmp2 idx df
idx__HB__division__gelderland__tmp2__df, idx__HB__division__gelderland__tmp2__count = HT_idx_df_func(
    gdf=habitat_kart__processed__gelderland__RD__gdf,
    idx_df=idx__AO__division__gelderland__tmp2__df,
    habitat_types_df=habitat_reference__WD__df,
    habitat_col='habitatType1'
)

idx__HB__division__website_plusHR__tmp2__df, idx__HB__division__website_plusHR__tmp2__count = HT_idx_df_func(
    gdf=habitat_kart__processed__website_plusHR__RD__gdf,
    idx_df=idx__AO__division__website_plusHR__tmp2__df,
    habitat_types_df=habitat_reference__WD__df,
    habitat_col='habitatType1'
)

In [25]:
# save
idx__HB__division__gelderland__tmp2__df.to_pickle(idx__HB__division__gelderland__tmp2__df_path)
idx__HB__division__website_plusHR__tmp2__df.to_pickle(idx__HB__division__website_plusHR__tmp2__df_path)

## Making IDX tables for FC (p80)

### IDX FC tmp1

In [26]:
# FC tmp1 IDX table
idx__FC__division__gelderland__tmp1__df, idx__FC__division__gelderland__tmp1__count = FC_idx_df_func(
    gdf=habitat_kart__processed__gelderland__RD__gdf,
    idx_df=idx__HB__division__gelderland__tmp1__df,
    min_percentage=100,
)

idx__FC__division__gelderland_minHR__tmp1__df, idx__FC__division__gelderland_minHR__tmp1__count = FC_idx_df_func(
    gdf=habitat_kart__processed__gelderland_minHR__RD__gdf,
    idx_df=idx__HB__division__gelderland_minHR__tmp1__df,
    min_percentage=100,
)

idx__FC__division__website__tmp1__df, idx__FC__division__website__tmp1_count = FC_idx_df_func(
    gdf=habitat_kart__processed__website__RD__gdf,
    idx_df=idx__HB__division__website__tmp1__df,
    min_percentage=100,
)

idx__FC__division__website_plusHR__tmp1__df, idx__FC__division__website_plusHR__tmp1__count = FC_idx_df_func(
    gdf=habitat_kart__processed__website_plusHR__RD__gdf,
    idx_df=idx__HB__division__website_plusHR__tmp1__df,
    min_percentage=100,
)

In [27]:
# Check FC tmp1 processing
values = [idx__FC__division__gelderland__tmp1__count, idx__FC__division__gelderland_minHR__tmp1__count,
          idx__FC__division__website__tmp1_count, idx__FC__division__website_plusHR__tmp1__count]
entities = ["gelderland", "gelderland_min_hr", "website", "website_plus_hr"]

check_processing(values, entities, typ="FC", tmp="tmp1")

['The number of habitat surveys is correct']

In [28]:
# Save
idx__FC__division__gelderland__tmp1__df.to_pickle(idx__FC__division__gelderland__tmp1__df_path)
idx__FC__division__gelderland_minHR__tmp1__df.to_pickle(idx__FC__division__gelderland_minHR__tmp1__df_path)
idx__FC__division__website__tmp1__df.to_pickle(idx__FC__division__website__tmp1__df_path)
idx__FC__division__website_plusHR__tmp1__df.to_pickle(idx__FC__division__website_plusHR__tmp1__df_path)

### IDX FC p80 tmp2

In [29]:
# FC tmp2 idx df
idx__FC_p80__division__gelderland__tmp2__df, idx__FC_p80__division__gelderland__tmp2__count = FC_idx_df_func(
    gdf=habitat_kart__processed__gelderland__RD__gdf,
    idx_df=idx__HB__division__gelderland__tmp2__df,
    min_percentage=80,
)

idx__FC_p80__division__website_plusHR__tmp2__df, idx__FC_p80__division__website_plusHR__tmp2__count = FC_idx_df_func(
    gdf=habitat_kart__processed__website_plusHR__RD__gdf,
    idx_df=idx__HB__division__website_plusHR__tmp2__df,
    min_percentage=80,
)

In [30]:
# Save
idx__FC_p80__division__gelderland__tmp2__df.to_pickle(idx__FC_p80__division__gelderland__tmp2__df_path)
idx__FC_p80__division__website_plusHR__tmp2__df.to_pickle(idx__FC_p80__division__website_plusHR__tmp2__df_path)

## Making IDX tables for WD

### IDX WD tmp1

In [31]:
# WD tmp1 idx df
idx__WD__division__gelderland__tmp1__df, idx__WD__division__gelderland__tmp1__count = group_idx_df_func(
    gdf=habitat_kart__processed__gelderland__RD__gdf,
    idx_df=idx__FC__division__gelderland__tmp1__df,
    habitat_types_df=habitat_reference__WD__df,
    habitat_col='habitatType1',
    group_col='WD_division'
)

idx__WD__division__gelderland_minHR__tmp1__df, idx__WD__division__gelderland_minHR__tmp1__count = group_idx_df_func(
    gdf=habitat_kart__processed__gelderland_minHR__RD__gdf,
    idx_df=idx__FC__division__gelderland_minHR__tmp1__df,
    habitat_types_df=habitat_reference__WD__df,
    habitat_col='habitatType1',
    group_col='WD_division'
)

idx__WD__division__website__tmp1__df, idx__WD__division__website__tmp1_count = group_idx_df_func(
    gdf=habitat_kart__processed__website__RD__gdf,
    idx_df=idx__FC__division__website__tmp1__df,
    habitat_types_df=habitat_reference__WD__df,
    habitat_col='habitatType1',
    group_col='WD_division'
)

idx__WD__division__website_plusHR__tmp1__df, idx__WD__division__website_plusHR__tmp1__count = group_idx_df_func(
    gdf=habitat_kart__processed__website_plusHR__RD__gdf,
    idx_df=idx__FC__division__website_plusHR__tmp1__df,
    habitat_types_df=habitat_reference__WD__df,
    habitat_col='habitatType1',
    group_col='WD_division'
)

In [32]:
# Check WD tmp1 processing
values = [idx__WD__division__gelderland__tmp1__count, idx__WD__division__gelderland_minHR__tmp1__count,
          idx__WD__division__website__tmp1_count, idx__WD__division__website_plusHR__tmp1__count]
entities = ["gelderland", "gelderland_min_hr", "website", "website_plus_hr"]

check_processing(values, entities, typ="WD", tmp="tmp1")

['The number of habitat surveys is correct']

In [33]:
# WD tmp1 IDX
idx__WD__division__gelderland__tmp1__df.to_pickle(idx__WD__division__gelderland__tmp1__df_path)
idx__WD__division__gelderland_minHR__tmp1__df.to_pickle(idx__WD__division__gelderland_minHR__tmp1__df_path)
idx__WD__division__website__tmp1__df.to_pickle(idx__WD__division__website__tmp1__df_path)
idx__WD__division__website_plusHR__tmp1__df.to_pickle(idx__WD__division__website_plusHR__tmp1__df_path)

## Making IDX tables for S1

### IDX S1 tmp1

In [34]:
# S1 tmp1 IDX table
idx__s1__division__gelderland__tmp1__df, idx__s1__division__gelderland__tmp1__count = group_idx_df_func(
    gdf=habitat_kart__processed__gelderland__RD__gdf,
    idx_df=idx__FC__division__gelderland__tmp1__df,
    habitat_types_df=habitat_reference__s__df,
    habitat_col='habitatType1',
    group_col='s1_division',
)

idx__s1__division__gelderland_minHR__tmp1__df, idx__s1__division__gelderland_minHR__tmp1__count = group_idx_df_func(
    gdf=habitat_kart__processed__gelderland_minHR__RD__gdf,
    idx_df=idx__FC__division__gelderland_minHR__tmp1__df,
    habitat_types_df=habitat_reference__s__df,
    habitat_col='habitatType1',
    group_col='s1_division',
)

idx__s1__division__website__tmp1__df, idx__s1__division__website__tmp1_count = group_idx_df_func(
    gdf=habitat_kart__processed__website__RD__gdf,
    idx_df=idx__FC__division__website__tmp1__df,
    habitat_types_df=habitat_reference__s__df,
    habitat_col='habitatType1',
    group_col='s1_division',
)

idx__s1__division__website_plusHR__tmp1__df, idx__s1__division__website_plusHR__tmp1__count = group_idx_df_func(
    gdf=habitat_kart__processed__website_plusHR__RD__gdf,
    idx_df=idx__FC__division__website_plusHR__tmp1__df,
    habitat_types_df=habitat_reference__s__df,
    habitat_col='habitatType1',
    group_col='s1_division',
)

In [35]:
# Check S1 tmp1 processing
values = [idx__s1__division__gelderland__tmp1__count, idx__s1__division__gelderland_minHR__tmp1__count,
          idx__s1__division__website__tmp1_count, idx__s1__division__website_plusHR__tmp1__count]
entities = ["gelderland", "gelderland_min_hr", "website", "website_plus_hr"]

check_processing(values, entities, typ="S1", tmp="tmp1")

['The number of habitat surveys is correct']

In [36]:
# s1 tmp1 IDX
idx__s1__division__gelderland__tmp1__df.to_pickle(idx__s1__division__gelderland__tmp1__df_path)
idx__s1__division__gelderland_minHR__tmp1__df.to_pickle(idx__s1__division__gelderland_minHR__tmp1__df_path)
idx__s1__division__website__tmp1__df.to_pickle(idx__s1__division__website__tmp1__df_path)
idx__s1__division__website_plusHR__tmp1__df.to_pickle(idx__s1__division__website_plusHR__tmp1__df_path)

In [37]:
idx__s1__division__gelderland__tmp1__df.head()

_year_str,2010-2016,2017,2018,2019,2020,2021,2022,2023,2024
Remaining,"[GI_1, GI_10, GI_10001, GI_10004, GI_10012, GI...","[GI_11616, GI_11633, GI_11635, GI_12300, GI_14...","[GI_11521, GI_13304, GI_14427, GI_150, GI_1819...","[GI_10067, GI_10074, GI_10078, GI_11378, GI_11...","[GI_10090, GI_10096, GI_10100, GI_10103, GI_10...","[GI_11242, GI_11297, GI_11299, GI_11301, GI_11...","[GI_13511, GI_13517, GI_13518, GI_13519, GI_13...","[GI_182, GI_183, GI_5352, GI_5396, GI_5397, GI...",[]
Vochtige heiden,"[GI_10557, GI_10585, GI_10604, GI_10747, GI_10...","[GI_41299, GI_41301, GI_41302, GI_41303, GI_41...","[GI_18984, GI_24214, GI_24216, GI_24221, GI_24...",[],"[GI_18750, GI_18785, GI_18790, GI_18804, GI_24...",[],[],[],[]
Zwakgebufferde vennen,"[GI_12829, GI_13961, GI_21272, GI_25818, GI_26...",[],"[GI_18556, GI_18985, GI_24217, GI_24230, GI_24...",[],"[GI_12951, GI_18483, GI_18774, GI_18777, GI_18...",[GI_18364],[],[],[]
Zure vennen,"[GI_12818, GI_12849, GI_12852, GI_12853, GI_12...",[GI_41726],[],[],"[GI_41774, GI_41775, GI_45813, GI_45820, GI_45...",[],[GI_45000],[],[]
Actieve hoogvenen (heideveentjes),"[GI_12854, GI_4517, GI_4525, GI_6037, GI_6164,...",[],"[GI_24249, GI_24294, GI_24977]",[],[],[],[],[],[]

End of the notebook